// 临时存储文件
export const searchPageData = {

	rockComposition: ['ultramafic', 'mafic', 'intermediate', 'felsic'],

	rockAlkalinity: ['alkaline(Irvine)', 'sub-alkaline(Irvine)', 'alkali-calcic(Frost)', 'alkalic(Frost)', 'calc-alkalic(Frost)', 'calcic(Frost)'],

	rockAttitude: ['volcanic', 'plutonic'],

	mineralSpotLocation: ['core', 'rim', 'zone'],

	experimentSampleType: ['experiment rock', 'experiment minral'],

	// 所有的大洲/海洋名称
	continent: [
		"Africa", "Antarctica", "Asia", "Oceania", "Europe", "North America", "South America",
		"Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Southern Ocean"
	],

	// 所有的国家名称
	countries: [
		"Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla",
		"Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan",
		"Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan",
		"Bolivia", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory",
		"Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
		"Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos Islands",
		"Colombia", "Comoros", "the Republic of the Congo", "the Democratic Republic of the Congo", "Cook Islands",
		"Costa Rica", "Côte d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
		"Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia",
		"Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
		"French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland",
		"Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
		"Heard Island and McDonald Islands", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia",
		"Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan",
		"Kenya", "Kiribati", "North Korea", "South Korea", "Kuwait", "Kyrgyzstan", "Lao People's Democratic Republic",
		"Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg",
		"Macao", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
		"Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
		"Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
		"Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island",
		"Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territory", "Panama", "Papua New Guinea",
		"Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Réunion", "Romania",
		"Russian Federation", "Rwanda", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Pierre and Miquelon",
		"Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
		"Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
		"South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard and Jan Mayen",
		"Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
		"Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
		"Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
		"United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Viet Nam", "The British Virgin Islands",
		"The United States Virgin Islands", "Wallis and Futuna", "Western Sahara", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe"
	],

	//   所有的纪元名称
	geologicalPeriods: [
		"Holocene", "Pleistocene-Upper", "Pleistocene-Middle", "Pleistocene-Calabrian", "Pleistocene-Gelasian", "Piacenzian", "Zanclean", "Messinian",
		"Tortonian", "Serravallian", "Langhian", "Burdigalian", "Aquitanian", "Chattian", "Rupelian", "Priabonian",
		"Bartonian", "Lutetian", "Ypresian", "Thanetian", "Selandian", "Danian", "Maastrichtian", "Campanian", "Santonian",
		"Coniacian", "Turonian", "Cenomanian", "Albian", "Aptian", "Barremian", "Hauterivian", "Valanginian", "Berriasian",
		"Tithonian", "Kimmeridgian", "Oxfordian", "Callovian", "Bathonian", "Bajocian", "Aalenian", "Toarcian", "Pliensbachian",
		"Sinemurian", "Hettangian", "Rhaetian", "Norian", "Carnian", "Ladinian", "Anisian", "Olenekian", "Induan",
		"Changhsingian", "Wuchiapingian", "Capitanian", "Wordian", "Roadian", "Kungurian", "Artinskian", "Sakmarian",
		"Asselian", "Gzhelian", "Kasimovian", "Moscovian", "Bashkirian", "Serpukhovian", "Visean", "Tournaisian", "Famennian",
		"Frasnian", "Givetian", "Eifelian", "Emsian", "Pragian", "Lochkovian", "Pridoli", "Ludfordian", "Gorstian", "Homerian", "Sheinwoodian",
		"Telychian", "Aeronian", "Rhuddanian", "Hirnantian", "Katian", "Sandbian", "Darriwilian", "Dapingian", "Floian",
		"Tremadocian", "Cambrian-Stage 10", "Jiangshanian", "Paibian", "Guzhangian", "Drumian", "Cambrian-Stage 5", "Cambrian-Stage 4", "Cambrian-Stage 3",
		"Cambrian-Stage 2", "Fortunian", "Ediacaran", "Cryogenian", "Tonian", "Stenian", "Ectasian", "Calymmian", "Statherian", "Orosirian",
		"Rhyacian", "Siderian", "Neo-archean", "Meso-archean", "Paleo-archean", "Eo-archean", "Hadean"
	],

	// age纪元对应的实际年龄下限
	geologicalAges: [
		0, 0.0117, 0.0126, 0.781, 1.8, 2.58, 3.6, 5.333, 7.246, 11.63, 13.82, 15.97, 20.44, 23.03, 28.1, 33.9, 37.8, 41.2, 47.8,
		56, 59.2, 61.6, 66, 72.1, 83.6, 86.3, 89.8, 93.9, 100.5, 113, 125, 129.4, 132.9, 139.8, 145, 152.1, 157.3, 163.5, 166.1,
		168.3, 170.3, 174.1, 182.7, 190.8, 199.3, 201.3, 208.5, 227, 237, 242, 247.2, 251.2, 252.17, 254.14, 259.8, 265.1, 268.8,
		272.3, 283.5, 290.1, 295, 298.9, 303.7, 307, 315.2, 323.2, 330.9, 346.7, 358.9, 372.2, 382.7, 387.7, 393.3, 407.6, 410.8,
		419.2, 423, 425.6, 427.4, 430.5, 433.4, 438.5, 440.8, 443.8, 445.2, 453, 458.4, 467.3, 470, 477.7, 485.4, 489.5, 494, 497,
		500.5, 504.5, 509, 514, 521, 529, 541, 635, 720, 1000, 1200, 1400, 1600, 1800, 2050, 2300, 2500, 2800, 3200, 3600, 4000, 4600
	],

	// 多选暂存
	terrane: [
		"ANDEAN ARC",
		"ARABIAN-NUBIAN SHIELD - PROTEROZOIC",
		"ARCHEAN CRATON (INCLUDING GREENSTONE BELTS)",
		"BISMARCK ARC - NEW BRITAIN ARC",
		"CENTRAL ASIAN FOLDBELT - CENOZOIC",
		"COMPLEX VOLCANIC SETTINGS",
		"CONTINENTAL FLOOD BASALT",
		"CONVERGENT MARGIN",
		"EMEISHAN",
		"EUROPEAN OROGENIC BELT - CENOZOIC",
		"HONSHU ARC",
		"HONSHU ARC / SOUTHWESTERN HONSHU ARC / SHIKOKU/SIKOKU",
		"INTRAPLATE VOLCANICS",
		"KAAPVAAL CRATON_MESOZOIC",
		"KAAPVAAL CRATON_MESOZOIC / SOUTH AFRICA / KIMBERLEY KIMBERLITE PROVINCE / BULTFONTEIN KIMBERLITE",
		"KAAPVAAL CRATON_MESOZOIC / SOUTH AFRICA / KIMBERLEY KIMBERLITE PROVINCE / KIMBERLEY KIMBERLITE",
		"KAAPVAAL CRATON_MESOZOIC / SOUTH AFRICA / KIMBERLEY KIMBERLITE PROVINCE / WESSELTON KIMBERLITE",
		"KAAPVAAL CRATON_PROTEROZOIC",
		"MASCARENE ISLANDS INCL. REUNION",
		"NAMAQUALAND NATAL BELT_MESOZOIC",
		"NORTH ATLANTIC IGNEOUS PROVINCE (NAIP)",
		"OCEAN ISLAND",
		"OCEAN-BASIN FLOOD BASALT",
		"OCEANIC PLATEAU",
		"RIFT VOLCANICS",
		"SAMOAN ISLANDS",
		"SEAMOUNT",
		"SUBMARINE RIDGE"
	],

	plate: [
		"African Plate",
		"Antarctic Plate",
		"Arabian Plate",
		"Australian Plate",
		"Caribbean Plate",
		"North American Plate",
		"Pacific Plate",
		"Scotia Plate"
	],

	rockNames: [
		"absarokite","adakite","alkali basalt","andesite","andesite basalt","ankaramite",
		"basalt","basaltic andesite","basaltic-andesite","basanite","benmoreite","boninite",
		"carbonatite","crinanite","dacite","diabase","diorite","dolerite","ferrobasalt",
		"ferropicrite","foidite","gabbro","granophyre","hawaiite","icelandite","ijolite","kamafugite",
		"keratophyre","komatiite","komatiite basalt","komatiitic basalt","lamproite","lamprophyre","latite",
		"leucitite","limburgite","madupite","malignite","melilitite","melilitolite","metatholeiite","minette",
		"mugearite","nephelinite","not-given","phonolite","phonotephrite","picrite","picrite-basalt","porphyrite",
		"pyroclastic-fall","pyroxenite","rhyolite","shoshonite","spilite","syenite","tephriphonolite","tephrite",
		"tholeiite","tholeiitic","tinguaite","trachyandesite","trachyandesite-basalt","trachybasalt","trachyte",
		"tristanite","tuff","websterite"
	],

	mineralNames: [
		"AL-SPINEL",
		"ALMANDINE",
		"ANDRADITE",
		"BRONZITE",
		"CHROME-SPINEL",
		"CHROMITE",
		"CLINOPYROXENE",
		"ENSTATITE",
		"FAYALITE",
		"FE-CHROMITE",
		"FERROHYPERSTHENE",
		"FERROSILITE",
		"FORSTERITE",
		"GAHNITE",
		"GARNET",
		"GROSSULAR",
		"HERCYNITE",
		"HYDROGARNET",
		"HYPERSTHENE",
		"JACOBSITE",
		"MAGNESIOFERRITE",
		"MAGNETITE",
		"MAGNETITE/CHROMITE",
		"MELANITE",
		"MONTICELLITE",
		"NOT-GIVEN",
		"OLIVINE",
		"ORTHOPYROXENE",
		"PICOTITE",
		"PLEONASTE",
		"PYROPE",
		"RINGWOODITE",
		"SCHORLOMITE",
		"SPINEL",
		"TITANO-MAGNETITE",
		"ULVOSPINEL"
	],

	sampleNames: [
		"silicate",
		"sulfide",
	],

	elementNamesForRock: [
		"Al2O3", "Ba", "CaO", "Ce", "Co", "Cr", "Cs", "Cu", "Dy", "Er", "Eu", "FeOT", "Ga", "Gd",
		"Hf", "Ho", "K2O", "La", "Lu", "MgO", "MnO", "Na2O", "Nb", "Nd", "Ni", "P2O5", "Pb", "Pr",
		"Rb", "Sc", "SiO2", "Sm", "Sr", "Ta", "Tb", "Th", "TiO2", "Tm", "U", "V", "Y", "Yb", "Zn", "Zr"
	],

	elementNamesForMineral: [
		"Al2O3",
		"Ba",
		"BaO",
		"CaO",
		"Ce",
		"CoO",
		"Cr",
		"Cr2O3",
		"Dy",
		"Er",
		"Eu",
		"Fe2O3",
		"FeO",
		"FeOT",
		"Gd",
		"Hf",
		"Ho",
		"K2O",
		"La",
		"Lu",
		"MgO",
		"MnO",
		"Na2O",
		"Nb",
		"Nb2O5",
		"Nd",
		"Ni",
		"NiO",
		"P2O5",
		"Pb",
		"Pr",
		"Rb",
		"Sc",
		"SiO2",
		"Sm",
		"Sr",
		"Ta",
		"Tb",
		"Th",
		"Ti",
		"TiO2",
		"Tm",
		"U",
		"V",
		"V2O3",
		"V2O5",
		"Y",
		"Yb",
		"ZnO",
		"Zr",
		"ZrO2"

	],

	elementNamesForExperiment: [
		"Al2O3",
		"CaO",
		"Cr2O3",
		"Cu2O",
		"Fe",
		"FeO",
		"H2O",
		"K2O",
		"MgO",
		"MnO",
		"Na2O",
		"Ni+Cu+Co",
		"NiO",
		"O",
		"P2O5",
		"S",
		"SiO2",
		"TiO2",
		"V2O5"
	],

	// 人名表
	firstAuthorForRock: [
	"ABDEL-RAHMAN A.-F. M.",
	"ABDULLAH  C. I.",
	"ABRAHAM A.-C.",
	"ABRATIS  M.",
	"ABU EL-ENENLRY M. M.",
	"AGOSTINI S.",
	"AGUILLON-ROBLES  A.",
	"AITCHISON J. C.",
	"AKA F. T.",
	"Albrecht/ Achim",
	"ALDANMAZ  E.",
	"ALENE  M.",
	"ALI K. A.",
	"ALIBERT  C.",
	"Alibert/ Chantal",
	"Allan-J-F",
	"ALLIBON  J.",
	"ALPASLAN M.",
	"ALRIC V. I.",
	"ALTHERR/ RAINER",
	"ALTUNKAYNAK  S.",
	"ANDERSON  R. G.",
	"ANDREASEN  R.",
	"ANDRONIKOV A. V.",
	"Anonymous",
	"ANTONINI  P.",
	"APPEL  P. W. U.",
	"ARMENDARIZ  M.",
	"ARMIENTI  P.",
	"ARNAUD N. O.",
	"ARNDT  N. T.",
	"ASMEROM  Y.",
	"AVANZINELLI  R.",
	"AWDANKIEWICZ  M.",
	"AYALEW D.",
	"AYDIN  F.",
	"AYUSO  R. A.",
	"AZIZI  H.",
	"Bacon-C-R",
	"Bacon-Charles-R",
	"BACON  C. R.",
	"Bacon/ Charles R",
	"BÃƒÂ‰DARD  J. H.",
	"Bailey-D-G",
	"Bailey-Michael-M",
	"Bailey-Roy-A",
	"BAKER  B. H.",
	"BAKER  J. A.",
	"BAKER  M. B.",
	"BAKER  P. E.",
	"Baker/ Michael B",
	"Baldridge-W-Scott",
	"Banks N G",
	"BARAGAR  W. R. A.",
	"BARBERIO  M. R.",
	"BARBOZA-GUDINO  J. R.",
	"Barker-F",
	"BARKER  F.",
	"BARKER A. K.",
	"BARRAT  J. A.",
	"BARRON L. M.",
	"BARRY  T. L.",
	"BASTA E. Z.",
	"BATIZA/ RODEY",
	"Beard/ Brian L",
	"BECCALUVA  L.",
	"BEIER  C.",
	"BEKTAS  O.",
	"BELL  B. R.",
	"BELLIENI G.",
	"BELLON  H.",
	"BENCE  A. E.",
	"BENOIT  M.",
	"Bergman/ Steven Clark",
	"BEYTH  M.",
	"BIANCHINI G.",
	"BIERLEIN  F. B.",
	"BIGIOGGERO B.",
	"BLAIS  S.",
	"BLANCHARD  M.-C.",
	"BLATTER D. L.",
	"Blatter D.L./ Farmer G. L./ Carmichael I.S.E.",
	"BLEIN  O.",
	"BLICHERT-TOFT  J.",
	"BLOOMER  S. H.",
	"BOARI E.",
	"BOCCALETTI  M.",
	"BOGAARD  P. J. F.",
	"BOLGE L. L.",
	"BONDRE  N. R.",
	"BOODEN M. A.",
	"Borg-Lars-E",
	"BORG  L. E.",
	"Bornhorst-Theodore-Joseph",
	"BOUABDLI A.",
	"BOUTONNET E.",
	"BOWERMAN  M.",
	"Bradshaw-T-K",
	"BRADSHAW  J. D.",
	"Bradshaw T K",
	"Bradshaw/ T K",
	"BRANCH C. D.",
	"Brandon-Alan-D",
	"BRANDON  A. D.",
	"BRIAND  B.",
	"BRIGGS  R. M.",
	"BROTZU P.",
	"BROWN  R. J.",
	"BRUESEKE M. E.",
	"BRYAN  S. E.",
	"BUCHELT  M.",
	"BUCHS D. M.",
	"BUKET  E.",
	"BULLEN  T. D.",
	"Bullen/ Thomas D",
	"CABANIS  B.",
	"CALMUS  T.",
	"Calmus T",
	"Calmus/ T",
	"Cameron-Kenneth-L",
	"CAMERON  K. L.",
	"CAMERON E. M.",
	"Cameron K L",
	"Cameron/ K L",
	"Campbell/ Steven Kent",
	"CANNATELLI  C.",
	"CAPALDI  G.",
	"CAPRARELLI  G.",
	"CARLSON R. W.",
	"Carmichael-I-S-E",
	"CARMICHAEL  I. S. E.",
	"CARR  M. J.",
	"CARR  P. F.",
	"CARRACEDO  J. C.",
	"CASTILLO  P. R.",
	"CASTORINA  F.",
	"CEBRIA  J.-M.",
	"CHABOU M. C.",
	"CHANDRASEKHARAM  D.",
	"CHANG J. M.",
	"CHASHCHIN  V. V.",
	"CHAUVEL  C.",
	"CHAZOT  G.",
	"CHE ZICHENG",
	"CHEN  CHENG-HONG",
	"CHEN  JU-CHIN",
	"CHEN CHENG-HONG",
	"CHEN DANLING",
	"CHERNET  T.",
	"CHUNG  SUN-LIN",
	"CHURIKOVA  T. G.",
	"CHUVASHOVA I. S.",
	"CIVETTA  L.",
	"CLASS  C.",
	"Clemens/ Drew Michael",
	"CLEMENT  J.-P.",
	"COBAN H.",
	"COISH  R. A.",
	"COLE  J. W.",
	"Colgan/ Joseph P.",
	"Colucci-M-T",
	"COLWELL  J. B.",
	"Conly A G",
	"CONLY A. G.",
	"Conrey-Richard-M",
	"CONTE  A. M.",
	"CONTICELLI S.",
	"COOK  C.",
	"CORNEN G.",
	"CORRIVEAU  L.",
	"CORSARO  R. A.",
	"COSTA  F.",
	"Cotten-J",
	"COUSENS  B. L.",
	"Cousens/ Brian",
	"Cousens/ Brian L",
	"CRAWFORD A. J.",
	"Creasey S C",
	"CRISCI G. M.",
	"CVETKOVIC  V.",
	"D^ANTONIO  M.",
	"D^ORAZIO M.",
	"DAOUD M. A.",
	"DAUTRIA J.-M.",
	"DAVIDSON  J. P.",
	"DAVIES  G. R.",
	"Davis-J",
	"Davis-Jon-M",
	"Davis-Linda-L",
	"DAVIS  A.",
	"DAVIS A. S.",
	"DAWOUD  M.",
	"DE ASTIS G.",
	"DE HOLLANDA M. H. B. M.",
	"DE MIN A.",
	"DE SOUZA Z. S.",
	"DELOR  C.",
	"DEMIDJUK Z.",
	"DENIEL  C.",
	"DERUELLE  B.",
	"DESSUREAU  G.",
	"DI BATTISTINI  G.",
	"DI GIROLAMO P.",
	"DICKIN  A. P.",
	"DIETRICH  V. J.",
	"DIMROTH  E.",
	"DING LIN",
	"DIXON  J. E.",
	"DONG YUEXIA",
	"DONGMO A. K.",
	"Donnelly-Nolan/ Julie M",
	"Donnelly-Nolan/ Julie M.",
	"DORENDORF  F.",
	"DOSTAL J.",
	"Dostal/ Jarda",
	"DOUCET  S.",
	"DOWNES  H.",
	"Draper/ David S",
	"DREHER  S. T.",
	"du Bray-Edward-A",
	"DUFFIELD  W. A.",
	"DUGDALE  A. L.",
	"DUGGEN S.",
	"Duke/ Genet I.",
	"Duncker-K-E",
	"DUNCKER  K. E.",
	"DUNGAN  M. A.",
	"DUPUY  C.",
	"DURASOVA  N. A.",
	"DUSEL-BACON  C.",
	"EHRENBERG  K.-H.",
	"Eiche-G-E",
	"EICHE  G.",
	"EL-SAYED  M. M.",
	"EL AZZOUZI M.",
	"EL BAKKALI S.",
	"EL SHESHTAWI Y. A.",
	"ELBURG M. A.",
	"ELLAM  R. M.",
	"ELLIOT  D. H.",
	"ELLIOTT T. R.",
	"ELY  J. C.",
	"EMBEY-ISZTIN  A.",
	"ERSOY  Y.",
	"Espindola-J-M",
	"EVINS L. Z.",
	"EWART A.",
	"FAN  WEI-MING",
	"FANG  NIANQIAO",
	"FANG  ZHONG",
	"Farmer-G-Lang",
	"FEDOROV  P. I.",
	"Feeley T C",
	"Feeley T.C.",
	"Feeley/ T C",
	"Feeley/ T.C.",
	"Ferrari-Luca",
	"Ferriz-Horacio",
	"FINGER  F.",
	"FITTON J. G.",
	"FLEMING  T. H.",
	"FLOYD  P. A.",
	"FODEN  J. D.",
	"FODOR R. V.",
	"FORD  A. B.",
	"FRAM  M. S.",
	"FRANCIS  D. M.",
	"FRANZ  G.",
	"FREDA C.",
	"FREERK-PARPATT M.",
	"FREY  F. A.",
	"FREYDIER  C.",
	"FREZZOTTI  M.-L.",
	"FRIMMEL  H. E.",
	"FURMAN T.",
	"FURNES  H.",
	"GÃƒÂœNGÃƒÂ–R  T.",
	"GAO  SHAN",
	"GAO YONGFENG",
	"Garcia-Palomo-A",
	"GARCIA M. O.",
	"GARLAND F. E.",
	"GEHRELS  G. E.",
	"GELDMACHER  J.",
	"GEMMELL  J. B.",
	"GENBUDO RESEARCH GROUP",
	"GENCALIOGLU-KUSCU  G.",
	"GEORGE  R. M. M.",
	"GERMA A.",
	"GERTISSER  R.",
	"Gest-D-E",
	"GIBB  F. G. F.",
	"Gibson-S-A",
	"GIBSON S. A.",
	"GILL  J. B.",
	"GILL R. C. O.",
	"GIONCADA A.",
	"GIORDANO  G.",
	"Glazner/ Allen F",
	"GOMEZ-TUENA  A.",
	"GRAJALES-NISHIMURA  J. M.",
	"GREENE  A. R.",
	"GREENTREE  M. R.",
	"GRENNE  T.",
	"GRODZICKI K. R.",
	"GROVE  T. L.",
	"Groves-Kristelle-Renee",
	"GU LIANXING",
	"GUEDES E.",
	"GUO  FENG",
	"GUO  ZHENGFU",
	"GUST  D. A.",
	"GUZMAN S. R.",
	"H. Mirnejad and K. Bell",
	"HAASE  K. M.",
	"HAILEAB  B.",
	"HAMELIN B.",
	"HAMILTON  T. S.",
	"HANANO D.",
	"HANGHOJ  K.",
	"HANSEN  H.",
	"HANSKI  E. J.",
	"HANYU  TAKESHI",
	"HARAGUCHI  S.",
	"HARANGI  S.",
	"HARMER  R. E.",
	"HARRIS  C.",
	"HART  S. R.",
	"HASTIE  A. R.",
	"HAUFF  F.",
	"HAURI  E. H.",
	"HE  YANHONG",
	"HE QI",
	"HE YANHONG",
	"HEINONEN  J. S.",
	"HELO  C.",
	"Henry-Christopher-D",
	"HERGT  J. M.",
	"Hildreth/ Wes prefacer",
	"Hill/ Brittain Eames",
	"HO  KUNG-SUAN",
	"HOANG N.",
	"Hochstaedter-Alfred-Glenn",
	"HOCHSTAEDTER  A. G.",
	"HOERNLE K. A.",
	"HOGG  A. J.",
	"HOLE  M. J.",
	"HOLM  P. M.",
	"Honjo/ Norio",
	"HONKAMO  M.",
	"Hooper-P-R",
	"HOOPER  P. R.",
	"HOPPER  D. J.",
	"HORNIG-KJARSGAARD  I.",
	"HORNIG  I.",
	"HOSONO  T.",
	"HOU  GUITING",
	"HOU GUANGSHUN",
	"HSU  CHU-NAN",
	"HUANG  HUA",
	"HUANG  S.",
	"HUANG  Y.-M.",
	"HUANG SHICHUN",
	"HUANG XIAO-LONG",
	"Hughes-Scott-S",
	"HUHMA H.",
	"HUMPHRIS  S. E.",
	"HUNTER  A. G.",
	"HYNES  A. J.",
	"IACUMIN  P.",
	"ICHIYAMA  Y.",
	"IKEDA  Y.",
	"INGLE  S. P.",
	"INNOCENT  C.",
	"INNOCENTI  F.",
	"ISHIWATARI  A.",
	"ISHIZUKA O.",
	"JACKSON  M. G.",
	"James-Eric-W",
	"JANNEY  P. E.",
	"JANOUSEK V.",
	"JARRAR  G. H.",
	"JENNER  G. A.",
	"JIANG  CHANGYI",
	"JIANG  YAO-HUI",
	"JICHA  B. R.",
	"JIMENEZ  N.",
	"JOLLY  W. T.",
	"JONES  G.",
	"Jordan-Brennan-T",
	"JORON  J.-L.",
	"JUNG S.",
	"KÃƒÂœRÃƒÂœM  S.",
	"KÃƒÂœRKCÃƒÂœOGLU  B.",
	"KALSBEEK  F.",
	"KAMENETSKY  V. S.",
	"KÃœRKCÃœOGLU B.",
	"KARMALKAR  N. R.",
	"KATZ  O.",
	"KATZIR  Y.",
	"KELLER  R. A.",
	"KELLEY  K. A.",
	"Kempton/ Pamela D",
	"KENT  R. W.",
	"KEPEZHINSKAS  P. K.",
	"KERR  A. C.",
	"KESKIN  M.",
	"KESSEL  R.",
	"KHALAF E. E. A. H.",
	"KITA  I.",
	"KITAGAWA  H.",
	"KLAUDIUS  J.",
	"KLEMENIC  P. M.",
	"Knox/ Katherine Lee",
	"KOBAYASHI  K.",
	"KOKFELT T. F.",
	"KONTER  J. G.",
	"KOPPERS  A. A. P.",
	"KRÃƒÂ–CHERT  J.",
	"KRIENITZ  M.-S.",
	"KRIVOLUTSKAYA N. A.",
	"KUEPOUO  G.",
	"KUNO  H.",
	"Kuntz/ Mel A",
	"KURITANI  T.",
	"KUSCHEL  E.",
	"LA FLECHE  M. R.",
	"LACASSE  C.",
	"LÃƒÂœ  YONGLUN",
	"LÃƒÂœ  ZHI-CHENG",
	"LAI  SHAOCONG",
	"LAI  YU-MING",
	"LAI SHAOCONG",
	"LAN  C.-Y.",
	"LANDING  E.",
	"Lang-James-Robert",
	"Lange-Rebecca-A",
	"LANGE  R. A.",
	"LAPIERRE  H.",
	"Lapierre/ Henriette",
	"LAROCQUE J.",
	"LARSEN  L. M.",
	"Lassiter-J-C",
	"Lassiter-John-C",
	"LASSITER  J. C.",
	"Latham Jr./ Thomas",
	"LE MASURIER  W. E.",
	"LE ROEX  A. P.",
	"LEASE N. A.",
	"Leat-P-T",
	"LEAT  P. T.",
	"Leeman-William-P",
	"LEGENDRE C.",
	"Leighty-Robert-Scott",
	"LESLIE  R. A. J.",
	"Lewis R",
	"Lewis R.S.",
	"Lewis/ R",
	"LEYBOURNE  M. I.",
	"LI  CHAOWEN",
	"LI  WU-XIAN",
	"LI  XIAN-HUA",
	"LI  XIAOYONG",
	"LI  ZHENG-XIANG",
	"LIANG  Y.",
	"LIAO  QUN^AN",
	"LIGHTFOOT  P. C.",
	"LIN  QIANG",
	"LIN GUANG-CHUN",
	"LINDSAY  J. M.",
	"Lindsay/ C R",
	"LING  WEN-LI",
	"Lipman/ Peter W",
	"LITVAK V. D.",
	"LIU  YONG-SHENG",
	"LONGARETTI G.",
	"LONGPRÃ‰ M.-A.",
	"LONIS  R.",
	"LOPEZ-ESCOBAR L.",
	"LOPEZ  J. C.",
	"LOPEZ DE LUCHI M. G.",
	"LOWENSTERN  J. B.",
	"LUCASSEN F.",
	"LUDDEN  J. N.",
	"Luhr-J-F",
	"Luhr-James-F",
	"LUHR  J. F.",
	"Luhr/ James F",
	"LUM  C. C. L.",
	"Lum/ Clinton C L",
	"LUNDSTROM  C. C.",
	"LUSTRINO M.",
	"LUTTINEN  A. V.",
	"LYLE  P.",
	"MA JIN-LONG",
	"MACDONALD  L. A.",
	"MACDONALD  R.",
	"MacDonald/ James H Jr",
	"MacDonald/ James H/ Jr",
	"MacLean-James-W",
	"MacLean-James-W.",
	"MACLENNAN  J.",
	"MADEIRA J.",
	"MAHMOUDI A.",
	"MAHONEY  J. J.",
	"MAILLET  P.",
	"MALUSKI  H.",
	"MAMANI M.",
	"MANGAN M. T.",
	"MANIKYAMBA  C.",
	"MANTHEI C. D.",
	"MARCELOT  G.",
	"MARQUES L. S.",
	"MARSHALL  L. P.",
	"Martin-Barajas/ Arturo",
	"MARTIN A.",
	"MARTIN E.",
	"Martiny B",
	"MARZOLI A.",
	"MASSEY  N. W. D.",
	"MATA J.",
	"MAURY  R. C.",
	"MAXEINER  R. O.",
	"MAZZUOLI R.",
	"MCBRIDE J. S.",
	"MCCARRON  J. J.",
	"McGee-J-J",
	"McKervey A.",
	"McMillan-N-J",
	"McMillan-Nancy-J",
	"Meen/ James K",
	"MEFFRE S.",
	"MEIFU  Z.",
	"MELEZHIK  V. A.",
	"MELLUSO  L.",
	"Meriggi L./ Macias J L/Tommasini S/ Capra L/ Conticelli S",
	"Meriggi/ L./ Macias/ J L/Tommasini/ S/ Capra/ L/ Conticelli/ S",
	"Mertzman/ Stanley A",
	"Metzger/ Ellen P",
	"MIHALIKOVA  A.",
	"Miller-Robert-J",
	"MILLER  CHRISTINE",
	"MILLER  D. M.",
	"MILLET M.-A.",
	"MILLWARD  D.",
	"MINCATO R. L.",
	"MIRNEJAD  H.",
	"Mirnejad/ H.",
	"Mitchell-Roger-H",
	"MIYAKE  Y.",
	"MO  XUANXUE",
	"MOGHAZI  A.-K. M.",
	"MOHAMED  F. H.",
	"MOLLEL G. F.",
	"MONTANINI A.",
	"MORA-KLEPEIS  G.",
	"MORI L.",
	"MORIOKA  K.",
	"MORRA  V.",
	"MORRIS  P. A.",
	"Morris/ George A",
	"MORRISON  M. A.",
	"MORTAJI A.",
	"MOSSMAN  D. J.",
	"MOURAO C.",
	"Muffler/ L J Patrick (prefacer)",
	"MUNGALL  J. E.",
	"MUNOZ  J. B.",
	"MURPHY  J. B.",
	"MUSHKIN  A.",
	"NAGAO  TAKASHI",
	"Nakada-Setsuya",
	"NAKAMURA  E.",
	"NAKASHIMA  T.",
	"NAREBSKI  W.",
	"NAZZARENI  S.",
	"Nealey/ L David",
	"Negendank-J-F-W",
	"Nelson-D-O",
	"Nelson-S-A",
	"Nelson-Stephen-A",
	"NELSON D. R.",
	"NEUMANN E.-R.",
	"NGOUNOUNO I.",
	"NICHOLSON  S. W.",
	"NIU  HE-CAI",
	"NJILAH  I. K.",
	"NKOUANDOU O. F.",
	"NKOUATHIO  D. G.",
	"NKOUMBOU  C.",
	"no author given",
	"NONO  A.",
	"Norman/ Marc D",
	"Novak/ S W",
	"NYSTRÃ–M J. O.",
	"O^REILLY  S. Y.",
	"OBEID M. A.",
	"OFFLER R.",
	"OMRANI  J.",
	"Ormerod-David-Stephen",
	"OROZCO-ESQUIVEL  M. T.",
	"ORSI G.",
	"PACES  J. B.",
	"PALAIS  J. M.",
	"Pallares/ Carlos",
	"PAMIC  J.",
	"PAONE  A.",
	"PAPEZIK  V. S.",
	"PAPPALARDO  L.",
	"Parker/ D F",
	"PARLAK  O.",
	"Patchett-J-P",
	"PATINO  L. C.",
	"PATOCKA  F.",
	"PAUL  B.",
	"Paz Moreno/ Francisco A",
	"PE-PIPER  G.",
	"PEARCE  J. A.",
	"PEATE  D. W.",
	"PECCERILLO A.",
	"Peck/ D L",
	"PEDERSEN  A. K.",
	"PENG  PENG",
	"PENG  TOUPING",
	"PERINI  G.",
	"PETRINI  R.",
	"Petrone-Chiara-M",
	"PHINNEY  W. C.",
	"PICCIRILLO  E. M.",
	"PIERCEY  S. J.",
	"PILET  S.",
	"PIN C.",
	"PINTSON  H.",
	"PIOCHI  M.",
	"PIPER  D. J. W.",
	"POLAT  A.",
	"POORNACHANDRA RAO  G. V. S.",
	"POPOV  V. K.",
	"POUCLET A.",
	"PRELEVIC  D.",
	"PRESTVIK  T.",
	"PRYTULAK J.",
	"PUFFER J. H.",
	"QI  LIANG",
	"RANKENBURG  K.",
	"RAY  ARIJITA.",
	"REAGAN  M. K.",
	"REICHOW  M. K.",
	"Reiners-Peter-W",
	"REINERS  P. W.",
	"RENNER  R.",
	"REVILLON  S.",
	"REYNAUD  C.",
	"REYNOLDS  R. W.",
	"RICHARDS  J. P.",
	"RILEY T. R.",
	"ROACH I. C.",
	"ROBILLARD  I.",
	"ROCCHI  S.",
	"RODRIGUEZ C.",
	"ROGERS N. W.",
	"Rogers/ N W",
	"ROMER  R. L.",
	"RONGA F.",
	"ROONEY T. O.",
	"ROTOLO  S. G.",
	"ROUCHON  V.",
	"ROWE  M. C.",
	"RUTHERFORD  L.",
	"SAMUEL M. D.",
	"SANCHEZ-GARCIA T.",
	"SANDEMAN  H. A.",
	"SANO  S.",
	"SANO  T.",
	"SATO  M.",
	"SAUNDERS  A. D.",
	"Saunders/ A D",
	"SAVOV I. P.",
	"SAVU  H.",
	"SCHELLEKENS  J. H.",
	"SCHMIDBERGER  S. S.",
	"SCHMINCKE  H.-U.",
	"SCHREIBER  U.",
	"Schucker-Dennis-E",
	"SCOATES  J. S.",
	"SEGHEDI  I.",
	"SEN  G.",
	"SERRI  G.",
	"SHAFER  J. T.",
	"SHEN  PING",
	"SHEPPARD  S.",
	"SHERATON  J. W.",
	"SHETH H. C.",
	"SHI  RENDENG",
	"SHINJO  R.",
	"SHIREY  S. B.",
	"SHUTO  K.",
	"Siebe-Claus",
	"SIEBEL W.",
	"Siebert-Lee",
	"SIEBERT  L.",
	"SIFETA K.",
	"SIMARD  R.-L.",
	"SIMPSON C. J.",
	"SIMS  K. W. W.",
	"SINGER B. S.",
	"SINTON  J. M.",
	"SIVELL  W. J.",
	"SKUF^IN  P. K.",
	"SKULSKI  T.",
	"SLATER  R. A.",
	"Smith-Eugene-I",
	"SMITH  A. D.",
	"SMITH  A. L.",
	"SMITH  D. R.",
	"SMITH  IAN E. M.",
	"SMITHIES  R. H.",
	"SOBEL  E. R.",
	"SOBOLEV  A. V.",
	"SOESOO  A.",
	"SOMMA  R.",
	"SONG  XIE-YAN",
	"SPÃƒÂ„TH  A.",
	"SPRUNG  P.",
	"SQUIRE R. J.",
	"STARKEY  N. A.",
	"STEFAN  A.",
	"STEIN  M.",
	"STEPHENSON  P. J.",
	"STERN  R. J.",
	"STEWART  K.",
	"Stockstill-Karen-R",
	"STOLZ  A. J.",
	"STOPPA  F.",
	"STOREY  M.",
	"STRAUB S. M.",
	"STRECK  M. J.",
	"Streck/ Martin J",
	"Stupak/ William A",
	"SUN  LiNHUA",
	"SUSHCHEVSKAYA N. M.",
	"SUTHERLAND  F. L.",
	"SWEENEY  R. J.",
	"SWINDEN  H. S.",
	"TADESSE  T.",
	"TAKAGI  T.",
	"TAKAMASA A.",
	"TAKASHIMA  REISHI",
	"TALAVERA MENDOZA O.",
	"TALUSANI R. V. R.",
	"TAMURA Y.",
	"TANG YAN-JIE",
	"TANKUT A.",
	"TARDY  M.",
	"TATSUMI  Y.",
	"TEKLAY  M.",
	"TEMIZEL  I.",
	"THIRLWALL  M. F.",
	"THOMAS  L. E.",
	"THOMAS  R. B.",
	"Thompson-R-N",
	"THOMPSON  M. D.",
	"THOMPSON  R. A.",
	"THOMPSON R. N.",
	"Thompson/ R N",
	"TIMM C.",
	"TOGASHI  S.",
	"TOKCAER  M.",
	"TONARINI  S.",
	"TORMEY D. R.",
	"TOSCANI  L.",
	"Trimble/ Donald E",
	"TRUA T.",
	"TRUMBULL R. B.",
	"TURNER S. P.",
	"ULRYCH  J.",
	"UPTON  B. G. J.",
	"Urbanczyk-Kevin-M",
	"USGS",
	"UTO  K.",
	"VALLIER  T. L.",
	"Van-Kooten-Gerald-K",
	"VAN DER ZANDER I.",
	"Varekamp-Johan-C",
	"VARNE  R.",
	"VAROL  E.",
	"Velasco-Tapia-Fernando",
	"VERATI C.",
	"VERGARA M. M.",
	"Verma-Surendra-P",
	"VERMA  S. P.",
	"VERMETTE  D. R.",
	"VESPA  M.",
	"Vetter/ Scott K",
	"VIDAL-SOLANO J. R.",
	"VIERECK  L. G.",
	"VOGEL  D. C.",
	"WADE  J. A.",
	"WÃƒÂ–RNER  G.",
	"WAGNER  T. P.",
	"Waits-J-R",
	"Walker-J-Douglas",
	"WALL  R. M.",
	"Wallace-Paul",
	"WALLACE  J. M.",
	"WANG  B.",
	"WANG  CHRISTINA YAN",
	"WANG  JIAN",
	"WANG  JIANG-HAI",
	"WANG  QIAN",
	"WANG  QIANG",
	"WANG  WEI",
	"WANG  XIAOLEI",
	"WANG  XUAN-CHE",
	"WANG  YUEJUN",
	"WANG XUAN-CHE",
	"WANG YUEJUN",
	"Ward-Robert-Lee",
	"WARK  D. A.",
	"WATTERS  B. R.",
	"WEAVER  S. D.",
	"WEDEPOHL  K. H.",
	"Weigand-Peter-W",
	"WEINSTEIN Y.",
	"WEIS  D.",
	"WEST  H. B.",
	"WHARTON  M. R.",
	"WHITE  R. V.",
	"WHITE JOHN C.",
	"White/ Craig M",
	"WIECHERT  U. H.",
	"Williams-Wendi-Joan-Whitehead",
	"WILLIAMS  H. M.",
	"WILSON  M.",
	"WILSON  R. A.",
	"WINCHESTER  J. A.",
	"WIRTH  K. R.",
	"WITTENBECHER  M.",
	"WITTENBRINK R.",
	"Wobus-Reinhard-A",
	"WOLDE  B.",
	"WOLFF  J. A.",
	"WOODHEAD  J. D.",
	"WORTHING M. A.",
	"WYMAN  D. A.",
	"XIA  LIN-QI",
	"XIAO  LONG",
	"XIONG  XIAO-LIN",
	"XU  BEI",
	"XU  DERU",
	"XU  JI-FENG",
	"XU  YI-GANG",
	"YALCIN  H.",
	"YAN  JUN",
	"YAN  QUANSHU",
	"YAN JUN",
	"YAXLEY  G. M.",
	"YILMAZ  Y.",
	"YING JI-FENG",
	"Yogodzinski-G-M",
	"YOKOYAMA  TETSUYA",
	"ZELLMER  G. F.",
	"ZHANG  HONG-FU",
	"ZHANG  JUN-JUN",
	"ZHANG  LIAN-CHANG",
	"ZHANG  MING",
	"ZHANG  XIAOHUI",
	"ZHANG  ZE-JUN",
	"ZHANG  ZHAOCHONG",
	"ZHANG HAIXIANG",
	"ZHANG MING",
	"ZHANG WENHUI",
	"ZHANG YU-TAO",
	"ZHANG ZHAOCHONG",
	"ZHAO  JIAN-XING",
	"ZHENG  YONG-FEI",
	"ZHENG JIAN-PING",
	"ZHI XIACHEN",
	"ZHOU  HAIMIN",
	"ZHOU  JIBIN",
	"ZHOU  JINCHENG",
	"ZHOU  MEI-FU",
	"ZHU  DI-CHENG",
	"ZHU  YONGFENG",
	"Zhu/Jun",
	"ZOU  HAIBO",
	],

	firstAuthorForMineral: [
		'ABDALLAH S. E.',
		'ABE N.',
		'ABLAY G. J.',
		'ABRATIS M.',
		'ABU EL-RUS M. A.',
		'ACEVEDO R. D.',
		'ACKERMAN L.',
		'ADACHI M.',
		'AGASHEV A. M.',
		'AGATA T.',
		'AGRANIER A.',
		'AGUIRRE-DIAZ G. J.',
		'AHIJADO A.',
		'AHMED A. H.',
		'AHMED-SAID Y.',
		'AITKEN B. G.',
		'AKAL C.',
		'AKELLA J.',
		'AKININ V. V.',
		'AKIZAWA N.',
		'ALBERT H.',
		'ALDANMAZ E.',
		'ALEMAYEHU M.',
		'ALI S.',
		'ALIANI P.',
		'ALLAN J. F.',
		'ALLETTI M.',
		'ALMEEV R. R.',
		'ALMEIDA V. V.',
		'ALTHAUS T.',
		'AMMA-MIYASAKA M.',
		'AMMON K.',
		'AMUNDSEN H. E. F.',
		'AN A-RIM',
		'AN YA-JUN',
		'ANAND M.',
		'ANDERSEN T.',
		'ANDERSON A. T. JR.',
		'ANDREEVA I. A.',
		'ANDREWS B. J.',
		'ANDRONIKOV A. V.',
		'ANDUJAR J.',
		'ANONYMOUS ...',
		'AOKI K.-I.',
		'APARICIO A. Y.',
		'APPLEYARD C. M.',
		'ARAI S.',
		'ARAKAWA Y.',
		'ARANA V.',
		'ARAUJO A. L. N.',
		'ARCULUS R. J.',
		'ARGUIN P.',
		'ARIENZO I.',
		'ARMIENTI P.',
		'ARMYTAGE R. M. G.',
		'ARNDT N. T.',
		'ARPA M. C. B.',
		'ARSLAN M.',
		'ARZAMASTSEV A. A.',
		'ASAMI M.',
		'ASHCHEPKOV I. V.',
		'ASHIKHMIN D. S.',
		'ASHWAL L. D.',
		'ASKREN D. R. R.',
		'ATLAS Z. D.',
		'ATZORI P.',
		'AUDETAT A.',
		'AUGE T.',
		'AULBACH S.',
		'AURISICCHIO C.',
		'AVANZINELLI R.',
		'AVELLAN D. R.',
		'AWDANKIEWICZ M.',
		'AYABE M.',
		'AYALEW D.',
		'AYDAR E.',
		'AYDIN F.',
		'AZAMBRE B.',
		'BAGDASSAROV N.',
		'BAGGERMAN T. D.',
		'BAILEY J. C.',
		'BAILEY K.',
		'BAITIS H. W.',
		'BAKER M. B.',
		'BAKHSH R. A.',
		'BALAGANSKAYA E.',
		'BALDRIDGE W. S.',
		'BALEN D.',
		'BALI E.',
		'BALLHAUS C.',
		'BAN M.',
		'BANNO S.',
		'BAPTISTE V.',
		'BARAGAR W. R. A.',
		'BARANYI I.',
		'BARBERI F.',
		'BARBIERI MARIO',
		'BARCLAY J.',
		'BARDINTZEFF J.-M.',
		'BARGOSSI G. M.',
		'BARKER A. K.',
		'BARLEY M. E.',
		'BARNES C. G.',
		'BARRAT J.-A.',
		'BARRERA J. L.',
		'BARRON L. M.',
		'BARSDELL M.',
		'BARSIKOV V. L.',
		'BARTON J. M. JR.',
		'BARTON M. D.',
		'BASCOU J.',
		'BASU A. R.',
		'BATIZA R.',
		'BAUDOUIN C.',
		'BAXTER A. N.',
		'BAZYLEV B. A.',
		'BEARD A. D.',
		'BECCALUVA L.',
		'BEDINI R. M.',
		'BEERMANN O.',
		'BEESON M. H.',
		'BEFUS K. S.',
		'BEHR W. M.',
		'BEIER C.',
		'BELLIENI G.',
		'BELLON H.',
		'BENAOUDA R.',
		'BENJAMIN E. R.',
		'BENSALAH M. K.',
		'BERGAL-KUVIKAS O.',
		'BERGER E. T.',
		'BERGER J.',
		'BERGMAN S. C.',
		'BERKESI M.',
		'BERLY T. J.',
		'BERNARD A.',
		'BERNSTEIN S.',
		'BERRY R. F.',
		'BERTRAND H.',
		'BEST M. G.',
		'BEYER E. E.',
		'BEZIAT D.',
		'BHANOT K. K.',
		'BIANCHINI G.',
		'BICKLE M. J.',
		'BIDYANANDA M.',
		'BILAL A.',
		'BILLER A. YA.',
		'BINARD N.',
		'BINDEMAN I. N.',
		'BINGEN B.',
		'BISHOP F.C.',
		'BIZIMIS M.',
		'BIZZARRO M.',
		'BJERG E. A.',
		'BLACK B. A.',
		'BLAIS S.',
		'BLAKE S.',
		'BLATTER D. L.',
		'BLOCH E.',
		'BLOOMER S. H.',
		'BLOOMFIELD A. L.',
		'BLUSZTAJN J.',
		'BOBROV A. V.',
		'BOCCALETTI M.',
		'BOCTOR N. Z.',
		'BOHRSON W. A.',
		'BOIVIN P.',
		'BONADIMAN C.',
		'BONATTI E.',
		'BONDI M.',
		'BOODEN M. A.',
		'BORLEY G. D.',
		'BORSUK A. M.',
		'BOSSHARD S. A.',
		'BOSSHARD-STADLIN S. A.',
		'BOUGAULT H.',
		'BOUILHOL P.',
		'BOURDIER J.-L.',
		'BOURGOIS J.',
		'BOUTONNET E.',
		'BOW C. S.',
		'BOYD F. R.',
		'BRAGAGNI A.',
		'BRAHM R.',
		'BRANDL P. A.',
		'BRANDON A. D.',
		'BRASCHI E.',
		'BRAUNGER S.',
		'BREARLEY M.',
		'BRENNA M.',
		'BRETON T.',
		'BRIGGS R. M.',
		'BROADLEY M. W.',
		'BROOKER R. A.',
		'BROOKS C. K.',
		'BROPHY J. G.',
		'BROTZU P.',
		'BROUSSE R.',
		'BROWN G. M.',
		'BROWN S. J. A.',
		'BROWNE B. L.',
		'BRUCE M. C.',
		'BRUECKNER H. K.',
		'BRYAN W. B.',
		'BRYANT J. A.',
		'BUCHOLZ C. E.',
		'BUCKLEY V. J. E.',
		'BUHLMANN A. L.',
		'BULLOCK L. A.',
		'BUNCH T. E.',
		'BURGESS S. R.',
		'BURNS D. H.',
		'BURT R. M.',
		'BUSREWIL M. T.',
		'BUSSWEILER Y.',
		'BYERLY B. L.',
		'CADOUX A.',
		'CAFFE P. J.',
		'CALANCHI N.',
		'CALLEGARI E.',
		'CAMBESES A.',
		'CAMEJO-HARRY M.',
		'CAMERON E. M.',
		'CAMUS G.',
		'CANIL D.',
		'CANNATELLI C.',
		'CAO JUN',
		'CAO L.-Q.',
		'CAPALDI G.',
		'CAPEDRI S.',
		'CAPRARELLI G.',
		'CARACCIOLO A.',
		'CARLIER G.',
		'CARLSON R. W.',
		'CARMICHAEL I. S. E.',
		'CARN S. A.',
		'CARO G.',
		'CAROFF M.',
		'CARPENTER R. L.',
		'CARRACEDO J. C.',
		'CARRACEDO SANCHEZ M.',
		'CARRASCO-NUNEZ G.',
		'CARSWELL D. A.',
		'CASAGLI A.',
		'CASETTA F.',
		'CASTILLO P. R.',
		'CASTOR S. B.',
		'CASTRO A.',
		'CASTRO DE MACHUCA B.',
		'CATHEY H. E.',
		'CATTELL A.',
		'CAWOOD P. A.',
		'CAWTHORN R. G.',
		'CENDRERO UCEDA A.',
		'CHAKHMOURADIAN A. R.',
		'CHAKRABARTY A.',
		'CHAKRABORTI T. M.',
		'CHALAPATHI RAO N. V.',
		'CHALOT-PRAT F.',
		'CHAMBERLAIN K. J.',
		'CHANDRASEKHARAM D.',
		'CHANG J. M.',
		'CHANG JIA',
		'CHANOUAN L.',
		'CHAPMAN N. A.',
		'CHASHCHIN A. A.',
		'CHATTERJEE N.',
		'CHATTOPADHYAYA S.',
		'CHAZOT G.',
		'CHEMINEE J.-L.',
		'CHEN BAO-YUN',
		'CHEN CHANG-HWA',
		'CHEN CHU-YUNG',
		'CHEN CHUNFEI',
		'CHEN DAOGONG',
		'CHEN HUAN',
		'CHEN JU-CHIN',
		'CHEN LIE-MENG',
		'CHEN MI-MI',
		'CHEN SHAOHAI',
		'CHEN SHENG-SHENG',
		'CHEN WEI',
		'CHEN XIAO-MING',
		'CHEN XIAODE',
		'CHENG ZHIGUO',
		'CHERTKOFF D. G.',
		'CHESNER C. A.',
		'CHEVREL M. O.',
		'CHIARADIA M.',
		'CHII S.',
		'CHIN E. J.',
		'CHMYZ L.',
		'CHOI HYUN-OK',
		'CHOI SUNG HI',
		'CHU ZHUYIN',
		'CHURIKOVA T. G.',
		'CIGOLINI C.',
		'CIMMINO F.',
		'CIONI R.',
		'CIVETTA L.',
		'CLAGUE D. A.',
		'CLEMENT J.-P.',
		'CLEVERLY R. W.',
		'CLOCCHIATTI R.',
		'CLYNNE M. A.',
		'COBAN H.',
		'COIRA B. L.',
		'COLE J. W.',
		'COLTORTI M.',
		'COLUCCI M. T.',
		'COMIN-CHIARAMONTI P.',
		'CONRAD W. K.',
		'CONREY R.M.',
		'CONTE A. M.',
		'CONTICELLI S.',
		'CONTINI S.',
		'COOMBS D. S.',
		'COOPER G. F.',
		'COOPER KARI M.',
		'CORNEN G.',
		'CORREALE A.',
		'CORSARO R. A.',
		'CORTES J. A.',
		'COSTA F. G.',
		'COTKIN S. J.',
		'COTTRELL E.',
		'COULON C.',
		'COX K. G.',
		'CRAWFORD A. J.',
		'CRECRAFT H. R.',
		'CREIGHTON S.',
		'CREON L.',
		'CRISP J. A.',
		'CRISTOFOLINI R.',
		'CROSSINGHAM T. J.',
		'CRUMMY J. M.',
		'CUCCINIELLO C.',
		'CUNDARI A.',
		'CVETKOVIC V.',
		'CWIEK M.',
		'CZAS J.',
		'DAHREN B.',
		'DAI BAO-ZHANG',
		'DAI FU-QIANG',
		'DAI HONG-KUN',
		'DAI LI-QUN',
		'DAI WEI',
		'DALRYMPLE G. B.',
		'DAMASCENO D.',
		'DANTAS C.',
		'DANYUSHEVSKY L. V.',
		'DAUTRIA J.-M.',
		'DAVI M.',
		'DAVIDSON J. P.',
		'DAVILA-HARRIS P.',
		'DAVIS A. S.',
		'DAWSON J. B.',
		'DAY J. M. D.',
		'DAY R. A.',
		'DE ASTIS G.',
		'DE BRUIN D.',
		'DE HOOG J. C. M.',
		'DE LIMA E. F.',
		'DE MOOR J. M.',
		'DE MULDER M.',
		'DE PABLO GALAN L.',
		'DE ROSA R.',
		'DE SILVA S. L.',
		'DE STEFANO A.',
		'DE VIVO B.',
		'DEBARI S. M.',
		'DEERING C. D.',
		'DEFANT M. J.',
		'DEGI J.',
		'DEL BELLO E.',
		'DEL MORO S.',
		'DELANEY J. S.',
		'DELONG S. E.',
		'DELOR C.',
		'DELPECH G.',
		'DEMANT A.',
		'DEMARCHI G.',
		'DEMENY A.',
		'DENG JINFU',
		'DENG LIXU',
		'DENG YUFENG',
		'DENIS C. M. M.',
		'DERUELLE B.',
		'DESHMUKH S. D.',
		'DESSAI A. G.',
		'DEVINE J. D.',
		'DEVITRE C. L.',
		'DI BATTISTINI G.',
		'DI CARLO I.',
		'DI GIROLAMO P.',
		'DI MARTINO C.',
		'DI MURO A.',
		'DI PIAZZA A.',
		'DI ROCCO T.',
		'DIETRICH H.',
		'DIEU J. J.',
		'DIJKSTRA A. H.',
		'DING LIN',
		'DIOH E.',
		'DIXON T. H.',
		'DJOUKAM J. F. T.',
		'DLUDLA S.',
		'DMITRIEV YU. I.',
		'DOBOSI G.',
		'DODGE F. C. W.',
		'DOGAN A. U.',
		'DOGAN-KULAHCI G. D.',
		'DOHERTY A. L.',
		'DONATTI-FILHO J. P.',
		'DONG JINLONG',
		'DONGRE A. N.',
		'DONNELLAN N. C. B.',
		'DONNELLY C. L.',
		'DONOGHUE S. L.',
		'DONSKAYA T. V.',
		'DORAIS M. J.',
		'DOROOZI R.',
		'DOROSHKEVICH A. G.',
		'DOSTAL J.',
		'DOUCET L. S.',
		'DOWNES H.',
		'DOYLE P. M.',
		'DRAPER D. S.',
		'DRUITT T. H.',
		'DU BRAY E. A.',
		'DU WEI',
		'DUAN XIAN-ZHE',
		'DUCEA M. N.',
		'DUDA A.',
		'DUNKL I.',
		'DUNWORTH E. A.',
		'DVORKIN A.',
		'DYGERT N.',
		'D^ANTONIO M.',
		'D^ORAZIO M.',
		'EASTON R. M.',
		'ECCLES R. R.',
		'ECHEVERRIA L. M.',
		'EDWARDS D.',
		'EGGINS S. M.',
		'EGOROV K. N.',
		'EHRENBERG K.-H.',
		'EICHE G.',
		'EISSEN J.-P.',
		'ELBURG M. A.',
		'ELKINS TANTON L. T.',
		'ELLIOT D. H.',
		'ELLIS B. S.',
		'ELTHON D.',
		'EMBEY-ISZTIN A.',
		'EMSLIE R.F.',
		'ENGLAND R. N.',
		'ERLANK A. J.',
		'ERSOY Y.',
		'ESENWEIN P.',
		'ESTRADE G.',
		'EVANS B. W.',
		'EWART A.',
		'EXLEY R. A.',
		'EYUBOGLU Y.',
		'FABRIES J.',
		'FAIRBROTHERS G. E.',
		'FALLOON T. J.',
		'FALUS G.',
		'FAN QICHENG',
		'FAN WEI-MING',
		'FANG NIANQIAO',
		'FARAHAT E. S.',
		'FAURE F.',
		'FEDELE F. G.',
		'FEDELE L.',
		'FEDERICO M.',
		'FEELEY T. C.',
		'FELDSTEIN S. N.',
		'FEMENIAS O.',
		'FENG WANYI',
		'FERGUSON A. K.',
		'FERGUSON M. R. M.',
		'FERLA P.',
		'FERLITO C.',
		'FERRACUTTI G.',
		'FERRANDO S.',
		'FERRY J. M.',
		'FERSHTATER G. B.',
		'FEYISSA D. H.',
		'FICHAUT M.',
		'FIELD L.',
		'FIELD S. W.',
		'FIELDING D. C.',
		'FIRTH C. W.',
		'FISK M. R.',
		'FITZPAYNE A.',
		'FODEN J. D.',
		'FODOR R. V.',
		'FOLEY N. K.',
		'FORNI F.',
		'FOURNELLE J. H.',
		'FRAM M. S.',
		'FRANCALANCI L.',
		'FRANCE L.',
		'FRANCIS D. M.',
		'FRECHEN J.',
		'FREERK-PARPATT M.',
		'FRENZEL G.',
		'FRETZDORFF S.',
		'FREUNDT A.',
		'FREY F. A.',
		'FREZZOTTI M.-L.',
		'FRISCH T.',
		'FROUDE D. O.',
		'FUJII T.',
		'FUJINAWA A.',
		'FULIGNATI P.',
		'FURMAN T.',
		'FURNES H.',
		'GAETA M.',
		'GAFFNEY A. M.',
		'GAGNEVIN D.',
		'GALAN G.',
		'GALER S. J. G.',
		'GALLO F.',
		'GALLOWAY M.',
		'GAMBLE J. A.',
		'GANDY M. K.',
		'GANGOPADHYAY A.',
		'GAO RUOHAN',
		'GAO SHAN',
		'GAO WENYUAN',
		'GAO YONGFENG',
		'GARCIA M. O.',
		'GARDE A. A.',
		'GARIEPY C.',
		'GARLAND F. E.',
		'GARRIDO C. J.',
		'GARRISON J. R. JR.',
		'GARUTI G.',
		'GASPARON M.',
		'GASPERINI D.',
		'GAVRYUSHKINA O. A.',
		'GAZEEV V. M.',
		'GEE J. S.',
		'GEIGER H.',
		'GELDMACHER J.',
		'GELMAN S. E.',
		'GENBUDO RESEARCH GROUP',
		'GENG XIANLEI',
		'GENSHAFT YU. S.',
		'GENSKE F. S.',
		'GENTILI S.',
		'GEOCHEMICAL STUDY OF LAVA FLOWS',
		'GEORGIEV S.',
		'GERBE M. C.',
		'GERKE T. L.',
		'GERLACH D. C.',
		'GERTISSER R.',
		'GESHI N.',
		'GHENT E. D.',
		'GHIARA M. R.',
		'GHORBANI M. R.',
		'GIANNETTI B.',
		'GIBB F. G. F.',
		'GIBSON R. G.',
		'GIEBEL R. J.',
		'GILBERT C. M.',
		'GILG H. A.',
		'GILL J. B.',
		'GIONCADA A.',
		'GIORDANO G.',
		'GIULIANI A.',
		'GLAHN A.',
		'GLASER S. M.',
		'GLAZOVSKAYA L. I.',
		'GLEESON M. L. M.',
		'GOGINENI S. V.',
		'GOLOVIN A. V.',
		'GOLUBKOVA A. B.',
		'GOMES C. B.',
		'GOMEZ-PUGNAIRE M. T.',
		'GONCHAREV A. G.',
		'GONZALES-JIMENEZ J. M.',
		'GORINI A.',
		'GORRING M. L.',
		'GOSS A. R.',
		'GOTO A.',
		'GOTO K. T.',
		'GOURGAUD A.',
		'GRAHAM I. J.',
		'GRANT T. B.',
		'GREAU Y.',
		'GREEN N. L.',
		'GREEN TREVOR H.',
		'GREENE A. R.',
		'GREENFIELD A. M. R.',
		'GREENOUGH J. D.',
		'GREGOIRE M.',
		'GRIB E. N.',
		'GRIFFIN W. L.',
		'GRUENDER K.',
		'GRUNDER A. L.',
		'GRUTZNER T.',
		'GU XIAO-YAN',
		'GUARINO V.',
		'GUILBAUD M.-N.',
		'GUNN B. M.',
		'GUO FENG',
		'GUO JIANGTAO',
		'GURENKO A. A.',
		'GURNEY J. J.',
		'GUZMAN S. R.',
		'GYORGY F.',
		'GYSI A. P.',
		'HAASE K. M.',
		'HAGGERTY S. E.',
		'HAGOS M.',
		'HALAMA R.',
		'HALL C. M.',
		'HAMDY M. M.',
		'HAMIDULLAH S.',
		'HAMILTON T. S.',
		'HAMMER J. E.',
		'HAMURO K.',
		'HAN YUE-SHENG',
		'HANDLEY H. K.',
		'HANGER B. J.',
		'HANSKI E. J.',
		'HANSTEEN T. H.',
		'HANYU TAKESHI',
		'HAO XI-LUO',
		'HAO YANTAO',
		'HARAGUCHI S.',
		'HARANGI R.',
		'HARDARDOTTIR V.',
		'HARI K. R.',
		'HARNOIS L.',
		'HARRIS C.',
		'HARRIS G. A.',
		'HARRIS N. B. W.',
		'HARTE B.',
		'HARTMANN G.',
		'HARVEY J.',
		'HASENAKA T.',
		'HASLAM H. W.',
		'HAURI E. H.',
		'HAUSER N.',
		'HAWKINS J. W. JR.',
		'HAYASHI S.',
		'HAYES B.',
		'HAYNES E. A.',
		'HE DETAO',
		'HEAMAN L. M.',
		'HEARN B. C. JR.',
		'HEIKEN G.',
		'HEINONEN J. S.',
		'HEINRICH W.',
		'HELIKER C.C.',
		'HELZ R. T.',
		'HEMING R. F.',
		'HEPWORTH L. N.',
		'HERNANDEZ J.',
		'HERNANDEZ-URIBE D.',
		'HERNANDO I. R.',
		'HERVIG R. L.',
		'HEYWORTH Z.',
		'HIDALGO S.',
		'HIGH-MAGNESIAN ANDESITES FROM THE NORTHWESTERN MARGIN OF THE PLIOCENE KUJU-BEPPU TECTONIC BASIN',
		'HILDRETH W.',
		'HILLS D. V.',
		'HIN R. C.',
		'HIRANO H.',
		'HIROTANI S.',
		'HO KUNG-SUAN',
		'HO R. A.',
		'HOANG T. H. A.',
		'HOCH M.',
		'HOFER H. E.',
		'HOLM P. M.',
		'HOLNESS M. B.',
		'HOLTZ F.',
		'HONG LU-BING',
		'HONG WENTAO',
		'HONJO N.',
		'HOOPER P. R.',
		'HOPS J. J.',
		'HORIUCHI T.',
		'HOSHINO M.',
		'HOSONO T.',
		'HOU TONG',
		'HOUGHTON R. L.',
		'HOUSH T. B.',
		'HOVORKA D.',
		'HOWARTH G. H.',
		'HU JUN',
		'HU YAN',
		'HUANG FANG',
		'HUANG HUA',
		'HUANG JIN-XIANG',
		'HUANG XIAO-LONG',
		'HUBER M. S.',
		'HUCKENHOLZ H. G.',
		'HUGHES D. J.',
		'HUGHES H. S. R.',
		'HUI HEJIU',
		'HUIJSMANS J. P. P.',
		'HUNT L.',
		'HUNTER R. H.',
		'HUSEN A.',
		'HUTCHISON M. T.',
		'HWANG P.',
		'H諰TT?P.',
		'IACUMIN P.',
		'ICHIYAMA Y.',
		'IKAWA T.',
		'IKEDA Y.',
		'IKEHATA K.',
		'IMAOKA T.',
		'IMSLAND P.',
		'INOMATA M.',
		'IONOV D. A.',
		'IRVING A. J.',
		'ISAKOVA A. T.',
		'ISHIBASHI K.',
		'ISHII T.',
		'ISHIKAWA A.',
		'ISHIMARU S.',
		'ISHIWATARI A.',
		'ISHIZAKI YASUO',
		'ISHIZUKA O.',
		'ISMAIL M.',
		'ITIGA Z.',
		'ITO J.',
		'IVANIKOV V. V.',
		'IWAMORI H.',
		'IZBEKOV P. E.',
		'IZBRODIN I. A.',
		'JACKSON C. G.',
		'JACOB D. E.',
		'JAGOUTZ E.',
		'JAKOBSSON S. P.',
		'JAN M. Q.',
		'JANKOVICS M. E.',
		'JANNEY P. E.',
		'JANOUSEK V.',
		'JAQUES A. L.',
		'JAVOY M.',
		'JEFFCOATE A. B.',
		'JEFFERY A. J.',
		'JIANG CHANGYI',
		'JIANG JIUYANG',
		'JIANG NENG',
		'JIANG YAO-HUI',
		'JIN ZHENMIN',
		'JING JIE-JUN',
		'JOHNS S. M.',
		'JOHNSON CLARK M.',
		'JOHNSON J. S.',
		'JOLIVET M.',
		'JONASSON K.',
		'JONES A. P.',
		'JORON J.-L.',
		'JOVANOVIC M.',
		'JUNG C.',
		'JUNG SEUNG GI',
		'KACZMAREK M.-A.',
		'KAESER B.',
		'KAHL M.',
		'KAHL WOLF-ACHIM',
		'KAKUBUCHI S.',
		'KALDOS R.',
		'KALINKIN M. M.',
		'KAMACI O.',
		'KAMENETSKY V. S.',
		'KAMGANG P.',
		'KAMINSKY F. V.',
		'KAMIYA K.',
		'KANAYAMA K.',
		'KANG JIN-TING',
		'KANO H.',
		'KARACIK Z.',
		'KARCHEVSKY P. I.',
		'KARGIN A. V.',
		'KARMALKAR N. R.',
		'KARPUKHINA E. V.',
		'KASAPOGLU B.',
		'KATO Y.',
		'KAWABATA H.',
		'KAWATE S.',
		'KAY S. M.',
		'KAYA O.',
		'KAYZAR T. M.',
		'KECHID S. A.',
		'KEIDING J. K.',
		'KELLER J.',
		'KELLER N. S.',
		'KEMPTON P. D.',
		'KENNEDY A. K.',
		'KEPEZHINSKAS P. K.',
		'KERR A. C.',
		'KERSTING A. B.',
		'KESHAV S.',
		'KESSON S.E.',
		'KHAN M. A.',
		'KHARBISH S.',
		'KHEZERLOU A. K.',
		'KHUBUNAYA S. A.',
		'KIENLE J.',
		'KIL Y.-W.',
		'KIM JIHYUK',
		'KIM NAK KYU',
		'KIM YOON KU',
		'KIMBALL K. L.',
		'KIMURA J.-I.',
		'KING B.-S. W.',
		'KINZLER R. J.',
		'KISEEVA E. S.',
		'KITAKAZE A.',
		'KITAYAMA Y. C.',
		'KLAVER M.',
		'KLEWIN K. W.',
		'KLUGEL A.',
		'KNITTEL-WEBER C.',
		'KOBAYASHI Y.',
		'KOCAARSLAN A.',
		'KOGARKO L. N.',
		'KOH J. S.',
		'KOHUT E. J.',
		'KOIZUMI K.',
		'KOLESNICHENKO M. V.',
		'KOMATSU M.',
		'KONC Z.',
		'KONECNY P.',
		'KONIG S.',
		'KONZETT J.',
		'KOORNNEEF J. M.',
		'KOPYLOVA M. G.',
		'KORESHKOVA M. YU.',
		'KORKMAZ G. G.',
		'KOROLEV N. M.',
		'KOSTERA A. Z.',
		'KOSTROVITSKY S. I.',
		'KOU C.',
		'KOURIM F.',
		'KOVACS I. J.',
		'KOVALENKO D. V.',
		'KOYAGUCHI T.',
		'KRATZMANN D. J.',
		'KRIENITZ M.-S.',
		'KRISHNAMURTHY P.',
		'KRIVOLUTSKAYA N. A.',
		'KROPAC K.',
		'KUANG GUANGXI',
		'KUBINOVA S.',
		'KUBO K.',
		'KUKULA A.',
		'KULP J. L.',
		'KUMAGAI Y.',
		'KUNUGIZA K.',
		'KURAT G.',
		'KURITANI T.',
		'KURKCUOGLU B.',
		'KURODA N.',
		'KUROKAWA K.',
		'KUSHENDRATNO ..',
		'KUSHIRO I.',
		'KUTSUKAKE T.',
		'KYLE P. R.',
		'KYSER T. K.',
		'LABOU I.',
		'LAEGER K.',
		'LAI SHAOCONG',
		'LAN CHING-YING',
		'LANGE R. A.',
		'LANYON R.',
		'LAPIERRE H.',
		'LARREA P.',
		'LARSEN J. F.',
		'LAUGHLIN A. W.',
		'LAURORA A.',
		'LAZAROV M.',
		'LAZKO E. E.',
		'LE BAS M. J.',
		'LE BEL L.',
		'LE MAITRE R. W.',
		'LE MASURIER W. E.',
		'LE MOIGNE J.',
		'LE ROEX A. P.',
		'LEBEDEV V. A.',
		'LEDNEVA G. V.',
		'LEE CIN-TY A.',
		'LEE DER-CHUEN',
		'LEE H. Y.',
		'LEE JEONG-A',
		'LEE MOON WON',
		'LEEMAN W. P.',
		'LEGENDRE C.',
		'LEHTONEN M.',
		'LEONARD G. S.',
		'LEONOR LAGORIO S.',
		'LERNER A. H.',
		'LESNOV F. P.',
		'LEWIS J. F.',
		'LI CHUSI',
		'LI HAI-YONG',
		'LI HAORAN',
		'LI HONGBO',
		'LI PEI',
		'LI WUPING',
		'LI XI-YAO',
		'LI XIAN-HUA',
		'LI YI-BING',
		'LI ZHENG-XUE',
		'LI ZILONG',
		'LIANG Y.',
		'LIATI A.',
		'LIERENFELD M. B.',
		'LIN ABING',
		'LINDSAY J. M.',
		'LINDSTROM M. M.',
		'LINTHOUT K.',
		'LIPTAI N.',
		'LISZEWSKA K. M.',
		'LITASOV K. D.',
		'LIU CHUAN-ZHOU',
		'LIU CONG-QIANG',
		'LIU JIA',
		'LIU SHEN',
		'LIU WEN-HAO',
		'LLOYD F. E.',
		'LOEWEN M. W',
		'LOGES A.',
		'LOGVINOVA A. M.',
		'LOHMAR S.',
		'LONGARETTI G.',
		'LONGPRE M.-A.',
		'LONIS R.',
		'LOPEZ J. C.',
		'LOPEZ M.',
		'LOPEZ RUIZ J.',
		'LORD A. B. H.',
		'LOSANTOS E.',
		'LOVERING J. F.',
		'LOWREY J. R.',
		'LU FENGXIANG',
		'LU JIANGGU',
		'LU LU',
		'LUALOVIRTA K.',
		'LUAN YAN',
		'LUBALA R. T.',
		'LUCASSEN F.',
		'LUCHS T.',
		'LUDDEN J. N.',
		'LUGUET A.',
		'LUHR J. F.',
		'LUKACS R.',
		'LUSTRINO M.',
		'MA GEORGE S.-K.',
		'MAALOE S.',
		'MACDONALD R.',
		'MACEDO FILHO A. A.',
		'MACIAS J. L.',
		'MACKENZIE J. M.',
		'MACLENNAN J.',
		'MACRIS C. A.',
		'MADUREIRA P.',
		'MAEHARA K.',
		'MAHOOD G. A.',
		'MAILLET P.',
		'MAKSIMOV S. O.',
		'MALARKEY J.',
		'MALAVIARACHCHI S. P. K.',
		'MAMBERTI M.',
		'MANDARANO M.',
		'MANDEVILLE C. W.',
		'MANN U.',
		'MANSUR A. T.',
		'MAO Y.-J.',
		'MARCHESI C.',
		'MARCHEV P.',
		'MARIANELLI P.',
		'MARKS M. A. W.',
		'MARLOW M. S.',
		'MARQUES L. S.',
		'MARQUEZ A.',
		'MARSH B. D.',
		'MARSHALL A. S.',
		'MARTEL C.',
		'MARTI J.',
		'MARTIN A. P.',
		'MARTINS S.',
		'MARZOLI A.',
		'MASON B.',
		'MASUN K. M.',
		'MATSUMOTO A.',
		'MATTEY D. P.',
		'MATTHEWS D. W.',
		'MATTIOLI M.',
		'MATTSSON H. B.',
		'MATUSIAK-MALEK M.',
		'MAURY R. C.',
		'MAXEINER R. O.',
		'MAZZEO F. C.',
		'MBASSA B. J.',
		'MBOWOU G. I. B.',
		'MCBIRNEY A. R.',
		'MCCALLUM M. E.',
		'MCCAMMON C. A.',
		'MCCARTHY A.',
		'MCCORMICK G. R.',
		'MCCOY-WEST A. J.',
		'MCCULLOCH M. T.',
		'MCCURRY M.',
		'MCGEE L. E.',
		'MCGREGOR V. R.',
		'MCINNES B. I. A.',
		'MCINTYRE T.',
		'MCIVER J. R.',
		'MCMAHON T. P.',
		'MEDARIS L. G.; JR.',
		'MEIJER A.',
		'MEKKAOUI A.',
		'MELCHIORRE M.',
		'MELEKESTSEV I. V.',
		'MELEKHOVA E.',
		'MELLUSO L.',
		'MELSON W. G.',
		'MENG FANXUE',
		'MENZIES A.',
		'MERIGGI L.',
		'MERLE R. E.',
		'MERRY M.',
		'MERTZMAN S. A. JR.',
		'MESHESHA D.',
		'METRICH N.',
		'MIKHAILENKO D. S.',
		'MIKHALSKY E. V.',
		'MIKLIUS A.',
		'MIKUS T.',
		'MILLER C.',
		'MILLER CHRISTINE',
		'MILLER M. L.',
		'MILOSKI P.',
		'MINISSALE S.',
		'MISHIN L. F.',
		'MITCHELL R. H.',
		'MITROPOULOS P.',
		'MIYAGI I.',
		'MIYAKE Y.',
		'MIYASHITA S.',
		'MIYOSHI M.',
		'MOGHADAM H. S.',
		'MOINE B. N.',
		'MOKHTARI A.',
		'MOLLEL G. F.',
		'MOLLO S.',
		'MONDAL S. K.',
		'MONJOIE P.',
		'MONNIER C.',
		'MONTANINI A.',
		'MOORE A. E.',
		'MOORE RICHARD B.',
		'MORA J. C.',
		'MORATTI G.',
		'MORI T.',
		'MORISHITA T.',
		'MORK M. B. E.',
		'MOROGAN V.',
		'MORRA V.',
		'MORRIS E. M.',
		'MOSSMAN D. J.',
		'MUES-SCHUMACHER U.',
		'MUIR I. D.',
		'MUKHERJEE S.',
		'MUKHOPADHAY B.',
		'MULLEN E. K.',
		'MUNDL-PETERMEIER A.',
		'MUNHA J.',
		'MUNOZ GARCIA MERCEDES',
		'MUNTEANU M.',
		'MURAKAMI N.',
		'MURAMATSU Y.',
		'MURAVYEVA N. S.',
		'MUROTA Y.',
		'MURPHY J. B.',
		'MYERS J. D.',
		'M腒IP哪 H.',
		'M躄LER DANIEL',
		'NADEAU O.',
		'NAGAO TAKASHI',
		'NAGASAKI H.',
		'NAKADA S.',
		'NAKAGAWA M.',
		'NAKAMURA Y.',
		'NAKANO S.',
		'NAKASHIMA T.',
		'NAKASHOLE A.',
		'NALDRETT A. J.',
		'NARANJO J. A.',
		'NARICI E.',
		'NASH W. P.',
		'NASIR S. J.',
		'NASLUND H. R.',
		'NATALI C.',
		'NATLAND J. H.',
		'NAUMOV V. B.',
		'NEAL C. R.',
		'NEAVE D. A.',
		'NEDLI Z.',
		'NEEDHAM A. J.',
		'NEHRU C. E.',
		'NEUKAMPF J.',
		'NEUMANN E.-R.',
		'NEWMAN S.',
		'NGONGE E. D.',
		'NGOUNOUNO I.',
		'NGUIHDAMA D.',
		'NGWA C. N.',
		'NICHOLLS I. A.',
		'NICOTRA E.',
		'NIELSEN T. F. D.',
		'NIELSON J. E.',
		'NIIDA K.',
		'NIKITINA L. P.',
		'NIKKOLA P.',
		'NIKOGOSIAN I. K.',
		'NIMIS P.',
		'NIMZ G. J.',
		'NINOMIYA A.',
		'NISBET E. G.',
		'NIU HE-CAI',
		'NIXON G. T.',
		'NJOMBIE M. P. W.',
		'NJONFANG E.',
		'NKOUANDOU O. F.',
		'NKOUATHIO D. G.',
		'NKOUMBOU C.',
		'NONO A.',
		'NORLING B.',
		'NORMAN M. D.',
		'NOVAK S. W.',
		'NOZAKA T.',
		'NTAFLOS T.',
		'NUREKI T.',
		'NUSBAUM R. L.',
		'NWE Y. Y.',
		'NYE C. J.',
		'OHARA Y.',
		'OHASHI F.',
		'OHBA T.',
		'OKAMURA H.',
		'ONUKI H.',
		'OOTES L.',
		'OREJANA D.',
		'ORLANDO A.',
		'OROZCO-ESQUIVEL M. T.',
		'ORSI G.',
		'ORSOEV D. A.',
		'OTAMENDI J. E.',
		'OTTONELLO G.',
		'OU QUAN',
		'OUZEGANE K.',
		'OWEN-SMITH T. M.',
		'OZAWA K.',
		'OZDEMIR Y.',
		'OZEROV A. YU.',
		'O^CALLAGHAN L. J.',
		'O^CONNOR T. K.',
		'O^REILLY S. Y.',
		'PAGANO D. S.',
		'PAL T.',
		'PAL-MOLNAR E.',
		'PALLADINO D. M.',
		'PALLISTER J. S.',
		'PAMIC J.',
		'PAN S.',
		'PAN SHAO-KUI',
		'PANDE K.',
		'PANG CHONG-JIN',
		'PANINA L. I.',
		'PANJASAWATWONG Y.',
		'PANTER K. S.',
		'PAPEZIK V. S.',
		'PAPP D. C.',
		'PARAT F.',
		'PARK KEUNSU',
		'PARKER D. F.',
		'PARKINSON I. J.',
		'PARLAK O.',
		'PARMAN S. W.',
		'PASSMORE E.',
		'PASTERIS J. D.',
		'PATEL S. C.',
		'PATTERSON D. S.',
		'PE-PIPER G.',
		'PEARCE J. A.',
		'PEARSON D. G.',
		'PEATE D. W.',
		'PECCERILLO A.',
		'PEDERSEN A. K.',
		'PELOROSSO B.',
		'PELTONEN P.',
		'PENG PENG',
		'PEREPELOV A. B.',
		'PERETYAZHKO I. S.',
		'PEREZ-SOBA C.',
		'PERINELLI C.',
		'PERINI G.',
		'PERKINS D.',
		'PERNET-FISHER J. F.',
		'PESLIER A. H.',
		'PETERS B. J.',
		'PETERSON T. D.',
		'PETROGENESIS OF KIMBERLITIC ROCKS AND ASSOCIATED XENOLITHS OF SOUTHEASTERN AUSTRALIA      F. R. BOYD',
		'PETRONE C. M.',
		'PHILPOTTS A. R.',
		'PIAIA P.',
		'PICHAVANT M.',
		'PIK R.',
		'PIMENTEL A.',
		'PINARELLI L.',
		'PINZUTI P.',
		'PIOCHI M.',
		'PIOLI L.',
		'PIPER D. J. W.',
		'PIVIN M.',
		'PLATEVOET B.',
		'PLATZ T.',
		'PLECHOV P. YU.',
		'POKA T.',
		'POKHILENKO N. P.',
		'POLAT A.',
		'POLYAKOV A. I.',
		'PONOMAREVA V. V.',
		'POPA R.-G.',
		'POPOV D. V.',
		'PORRECA C.',
		'PORTNYAGIN M. V.',
		'POTTER N. J.',
		'PRAEGEL N.-O.',
		'PRELEVIC D.',
		'PRESS S.',
		'PRESTVIK T.',
		'PRINCIVALLE F.',
		'PRITCHARD C. J.',
		'PROSSER G.',
		'PRUEHER L. M.',
		'PRYCHODKO M.',
		'PUCHTEL I. S.',
		'PUNTURO R.',
		'PUSHKAREV E. V.',
		'PUTIRKA K. D.',
		'PUZIEWICZ J.',
		'QI QU',
		'QIAN ZHUANGZHI',
		'RADIVOJEVIC M.',
		'RADU I.-B.',
		'RAFFONE N.',
		'RAGOZIN A. L.',
		'RAJESH H. M.',
		'RAMESHWAR RAO D.',
		'RAMOS F. C.',
		'RAMPONE E.',
		'RAMSEY W. R. H.',
		'RANKENBURG K.',
		'RASMUSSEN D. J.',
		'RATSCHBACHER B. C.',
		'RAVNA E. J. K.',
		'RAWLINSON P. J.',
		'RAY ARIJITA',
		'REAGAN M. K.',
		'REDDY T. A. K.',
		'REHFELDT T.',
		'REID A. M.',
		'REN MINGHUA',
		'RENNER R.',
		'RENZULLI A.',
		'REUBI O.',
		'REVILLON S.',
		'REYES J.',
		'REYNOLDS R. W.',
		'REZEAU H.',
		'RHODES J. M.',
		'RIBEIRO J. M.',
		'RICHARDS J. P.',
		'RICHES A. J. V.',
		'RIDLEY W. I.',
		'RIGHTER K.',
		'RILLEY T. R.',
		'RISSE A.',
		'RIVALENTI G.',
		'RIVERA M.',
		'ROCCO I.',
		'ROCHA DE MACEDO J.',
		'ROCKOW K. M.',
		'RODRIGUEZ C.',
		'RODRIGUEZ-LOSADA J. A.',
		'ROGER S.',
		'ROGERS A. J.',
		'ROHRBACH A.',
		'ROLLAND Y.',
		'ROLLINSON H. R.',
		'ROMAN D. C.',
		'ROMICK J. D.',
		'RONGA F.',
		'ROONEY T. O.',
		'ROSATELLI G.',
		'ROSE W. I. JR.',
		'ROSI M.',
		'ROSS C. S.',
		'ROWBOTHAM G.',
		'RUAN BANXIAO',
		'RUBENACH M. J.',
		'RUDEK E. A.',
		'RUDNICK R. L.',
		'RUTTER E. H.',
		'RYABCHIKOV I. D.',
		'RYABOV V. V.',
		'SAADAT S.',
		'SAAL A. E.',
		'SAALFELD M. A.',
		'SABLUKOV S. M.',
		'SAGE R. P.',
		'SAGREDO RUIZ J.',
		'SAHAMA T. G.',
		'SAITO G.',
		'SAJID M.',
		'SAJONA F. G.',
		'SAKAYORI A.',
		'SAKHNO V. G.',
		'SAKUYAMA M.',
		'SALTZER R. L.',
		'SALVIOLI-MARIANI E.',
		'SALVIULO G.',
		'SAMANIEGO P.',
		'SAMUEL V. O.',
		'SAN JOSE M. L.',
		'SAND K. K.',
		'SANDEMAN H. A.',
		'SANO T.',
		'SANTACROCE R.',
		'SANTO A. P.',
		'SANTOSH M.',
		'SAPIENZA G. T.',
		'SARKAR C.',
		'SARRIONANDIA F.',
		'SAS M.',
		'SATSUKAWA T.',
		'SAUNDERS A. D.',
		'SAVATENKOV V. M.',
		'SAVELYEVA V. B.',
		'SAVOV I. P.',
		'SAWADA Y.',
		'SCARLATO P.',
		'SCHAAF P.',
		'SCHIANO P.',
		'SCHIAVI F.',
		'SCHILLING M. E.',
		'SCHMADICKE E.',
		'SCHMICKLER B.',
		'SCHMIDBERGER S. S.',
		'SCHMIDT M. E.',
		'SCHMINCKE H.-U.',
		'SCHMITT A. K.',
		'SCHNEIDER K. P.',
		'SCHULZE D. J.',
		'SCOON R. N.',
		'SCOTT B.',
		'SCOTT J. A. J.',
		'SCOTT SMITH B. H.',
		'SCRIBANO V.',
		'SEAMAN S. J.',
		'SECCO L.',
		'SECHER K.',
		'SEGHEDI I.',
		'SEKISOVA V. S.',
		'SELF S.',
		'SELIGMAN A. N.',
		'SEMIZ B.',
		'SEN G.',
		'SEN I. S.',
		'SENDA R.',
		'SERRI G.',
		'SETERA J.',
		'SETHNA S. F.',
		'SEVERS M. J.',
		'SEWELL R. J.',
		'SEYMOUR K. ST.',
		'SGARBI P. B. A.',
		'SGUALDO P.',
		'SHAIKH A. M.',
		'SHAMBERGER P. J.',
		'SHANE P. A.',
		'SHAO JI-AN',
		'SHARASKIN A. YA.',
		'SHARKOV E. V.',
		'SHARYGIN V. V.',
		'SHAW C. S. J.',
		'SHAW J. E.',
		'SHCHEKA S. A.',
		'SHCHERBAKOV YU. D.',
		'SHCHUKINA E. V.',
		'SHE YU-WEI',
		'SHEE S. R.',
		'SHEEHAN F.',
		'SHEN JI',
		'SHERATON J. W.',
		'SHI L.',
		'SHIDO F.',
		'SHIMAZU M.',
		'SHINJO R.',
		'SHIRAKI K.',
		'SHU CHUTIAN',
		'SHU QIAO',
		'SHUKUNO H.',
		'SHUTO K.',
		'SIBIK S.',
		'SIEBEL W.',
		'SIEGRIST M.',
		'SIENA F.',
		'SIGMARSSON O.',
		'SIGURDSSON H.',
		'SILANTEV S. A.',
		'SIMAKOV S. K.',
		'SIMON N. S. C.',
		'SIMONETTI A.',
		'SINDERN  S.',
		'SINGER B. S.',
		'SISSON T. W.',
		'SKEWES M. A.',
		'SMART K. A.',
		'SMIRNOV S. Z.',
		'SMIT K. V.',
		'SMITH A. L.',
		'SMITH B. H. C.',
		'SMITH D.',
		'SMITH I. E. M.',
		'SMOL^KIN V. F.',
		'SMULIKOWSKI K.',
		'SOBOLEV N. V.',
		'SOLOVJEVA L. V.',
		'SOLTYS A.',
		'SOMMER H.',
		'SONG YAN',
		'SOSA-CEBALLOS G.',
		'SOTTILI G.',
		'SOUTHER J. G.',
		'SOYA T.',
		'SPACEK P.',
		'SPADEA P.',
		'SPAETH A.',
		'SPANDLER C. J.',
		'SPENGLER D.',
		'SPETSIUS Z. V.',
		'STAMM N.',
		'STEAD C. V.',
		'STEIN M.',
		'STEPANOVA A. V.',
		'STEPHENSON D.',
		'STERN C. R.',
		'STEWART R. B.',
		'STIEFENHOFER J.',
		'STIEGLER M. T.',
		'STOCKSTILL K. R.',
		'STOLZ A. J.',
		'STONE W. E.',
		'STOPPA F.',
		'STOSCH H.-G.',
		'STRAUB S. M.',
		'STRECK M. J.',
		'SU BEN-XUN',
		'SU YUPING',
		'SUBBA RAO D. V.',
		'SUH C. E.',
		'SUMITA M.',
		'SUN HE',
		'SUN JING',
		'SUN MINGDAO',
		'SUN TAO',
		'SUN YANG',
		'SUNKEL G.',
		'SUTHERLAND F. L.',
		'SUTTHIRAT C.',
		'SUZUKI Y.',
		'SVISERO D. P.',
		'SVOJTKA M.',
		'SWALLOW E. J.',
		'SWANSON S. E.',
		'SWEENEY R. J.',
		'SZABO C.',
		'TAGIRI M.',
		'TAINOSHO Y.',
		'TAKAGI T.',
		'TAKAHASHI E.',
		'TAKAHASHI YUTAKA',
		'TAKAZAWA E.',
		'TAKEBE Y.',
		'TAKEUCHI M.',
		'TAMEN J.',
		'TANAKA S.',
		'TANG DONG-MEI',
		'TANG QINGYAN',
		'TANG YAN-JIE',
		'TANGUY J.-C.',
		'TAO YAN',
		'TAPPE S.',
		'TAPPEN C. M.',
		'TAPPERT R.',
		'TARARIN I. A.',
		'TARDY M.',
		'TATSUMI Y.',
		'TAYLOR R. N.',
		'TAZAKI K.',
		'TCHAPTCHET D. T.',
		'TECCHIATO V.',
		'TEKLAY M.',
		'TEMEL A.',
		'TEMIZEL I.',
		'TEPLEY F. J.; III',
		'THAKURDIN Y.',
		'THANH N. X.',
		'THI T. N.',
		'THIRLWALL M. F.',
		'THOMPSON GARY M.',
		'THORARINSSON S. B.',
		'THORNBER C. R.',
		'THY P.',
		'TIMINA T. YU.',
		'TIMM C.',
		'TOKUYAMA H.',
		'TOLLAN P. M. E.',
		'TOLSTYKH M. L.',
		'TOMANIKOVA L.',
		'TONARINI S.',
		'TONG XIN',
		'TOOTHILL J.',
		'TORMEY D. R.',
		'TORNARE E.',
		'TOROK.',
		'TOSCANI L.',
		'TOURON S.',
		'TOYA N.',
		'TRACY R. J.',
		'TRIBUZIO R.',
		'TRIGILA R.',
		'TROCH J.',
		'TROENNES R. G.',
		'TRUA T.',
		'TRUMBULL R. B.',
		'TSCHEGG C.',
		'TSUCHIYA NOBUTAKA',
		'TSVETKOV A. A.',
		'TSYGANKOV A. A.',
		'TSYPUKOV M. YU.',
		'TULLOCH A. J.',
		'TURBEVILLE B. N.',
		'TURNER M. B.',
		'TURNER SIMON P.',
		'TURUNEN S. T.',
		'TYCHKOV N. S.',
		'UCHIDA T.',
		'UCHIMIZU M.',
		'UEKI K.',
		'UENVER-THIELE L.',
		'UJIKE O.',
		'ULIANOV A.',
		'ULRYCH J.',
		'UMINO S.',
		'UPTON B. G. J.',
		'UYSAL I. T.',
		'VAGGELLI G.',
		'VALERA G. T. V.',
		'VAN ACHTERBERGH E.',
		'VAN ACKEN D.',
		'VAN BERGEN M. J.',
		'VAN DER LAAN S. R.',
		'VAN KOOTEN G. K.',
		'VANNUCCI R.',
		'VANTONGEREN J. A.',
		'VAREKAMP J. C.',
		'VARNE R.',
		'VAROL E.',
		'VARTIAINEN H.',
		'VASELLI O.',
		'VASIL^EV YU. R.',
		'VATIN-PERIGNON N.',
		'VAZQUEZ J. A.',
		'VEKSLER I. V.',
		'VELDE D.',
		'VENEZKY D. Y.',
		'VENTURELLI G.',
		'VERHULST A.',
		'VERNIKOVSKAYA A. E.',
		'VICCARO M.',
		'VIDAL-SOLANO J. R.',
		'VILJOEN F.',
		'VILJOEN K. S.',
		'VILLARI L.',
		'VILLASECA C.',
		'VOGEL T. A.',
		'VOLLMER R.',
		'VOLYNETS O. N.',
		'VRUBLEVSKII V. V.',
		'WAGNER C.',
		'WAGNER T. P.',
		'WALKER B. A.',
		'WALLACE P. J.',
		'WANG CHENGYUAN',
		'WANG DAN',
		'WANG DONG-YAN',
		'WANG RUI-QIANG',
		'WANG WIN',
		'WANG XUAN-CHE',
		'WANG ZHENGRONG',
		'WASILEWSKI B.',
		'WATANABE K.',
		'WATANABE TERUO',
		'WATTS K. E.',
		'WEBER M. B. I.',
		'WEHRMANN H.',
		'WEI QIRONG',
		'WEI YING',
		'WEIBLEN P. W.',
		'WEIDENDORFER D.',
		'WEINSTEIN J. P.',
		'WEIS D.',
		'WEST W. D.',
		'WESTGATE J. A.',
		'WEYER S.',
		'WHELLER G. E.',
		'WHITE C. M.',
		'WHITE JOHN C.',
		'WIECHERT U. H.',
		'WILKINSON J. F. G.',
		'WILSHIRE H. G.',
		'WINPENNY B.',
		'WITT G.',
		'WITT W. K.',
		'WITT-EICKSCHEN G.',
		'WITTENBRINK R.',
		'WITTER J. B.',
		'WOLFE E. W.',
		'WOO YONGHOON',
		'WOODLAND A. B.',
		'WRIGHT E.',
		'WRIGHT T. L.',
		'WU DAN',
		'WU FU-YUAN',
		'WU G. Y.',
		'WULFF-PEDERSEN E.',
		'WYERS G. P.',
		'WYMAN D. A.',
		'WNER G.',
		'XIA PING',
		'XIA QIONGXIA',
		'XIA QUN-KE',
		'XIE GUANGHONG',
		'XIE QIUHONG',
		'XIONG QING',
		'XU GUANGPING',
		'XU HAIJIN',
		'XU RONG',
		'XU WEN-LIANG',
		'XU XISHENG',
		'XU YI-GANG',
		'XU YONGJIANG',
		'XU YUE',
		'XUE SHUO',
		'YAJIMA K.',
		'YALCIN H.',
		'YAMAGUCHI M.',
		'YAMAMOTO J.',
		'YAMAMOTO MASATSUGU',
		'YAMASAKI T.',
		'YAN JUN',
		'YANG H. Y.',
		'YANG HUAI-JEN',
		'YANG JINHUI',
		'YANG KYOUNGHEE',
		'YANG LIMING',
		'YANG SHENG-HONG',
		'YANG XIAO-ZHI',
		'YASUI M.',
		'YAXLEY G. M.',
		'YAZAR E. A.',
		'YAZDANI S.',
		'YING JI-FENG',
		'YOKOYAMA K.',
		'YOSHIKAWA M.',
		'YOUNG E. D.',
		'YU HONG-MEI',
		'YU HUIMIN',
		'YU JINHAI',
		'YU SONG-YUE',
		'YU XUEHUI',
		'YUAN QIAN',
		'YUN SUNGHYO',
		'YURTMEN S.',
		'YEL C.',
		'ZAITSEV A. N.',
		'ZAJACZ Z.',
		'ZAKARIADZE G. S.',
		'ZANETTIN B.',
		'ZANON V.',
		'ZAPPETTINI E. O.',
		'ZEDGENIZOV D. A.',
		'ZELENSKI M. E.',
		'ZENG GANG',
		'ZHANG CHAO',
		'ZHANG G. S.',
		'ZHANG HAIDONG',
		'ZHANG HONG-FU',
		'ZHANG HUI',
		'ZHANG JIN',
		'ZHANG YAN-LONG',
		'ZHANG YUNYING',
		'ZHANG ZHAOCHONG',
		'ZHAO XIN-MIAO',
		'ZHAO YUN',
		'ZHAO ZHEN-HUA',
		'ZHAO ZHIDAN',
		'ZHENG JIAN-PING',
		'ZHOU JINCHENG',
		'ZHOU QIN',
		'ZHOU QUNJUN',
		'ZHU YONGFENG',
		'ZHU YUSHENG',
		'ZHUKOVA I. A.',
		'ZIBERNA L.',
		'ZIMMER M. M.',
		'ZINNGREBE E.',
		'ZIPFEL J.',
		'ZLOBIN S. K.',
		'ZOBIR S. H.',
		'ZOLOTUKHIN V. V.',
		'ZOU DONGYA',
		'ZOU HAIBO',
		'ZUREVINSKI S. E.',
	],

	firstAuthorForExperiment: [
		"Blanchard",
		"Brenan",
		"D'Souza",
		"Ding",
		"Fortin",
		"Gaetani",
		"Holzheid",
		"Jugo",
		"Kang",
		"Kiseeva",
		"Laurenz",
		"Liu",
		"Mavrogenes",
		"O'Neill",
		"Peach",
		"Ripley",
		"Smythe",
		"Steenstra",
		"Wendlandt",
		"Wohlers",
		"Wood"
	],

	journalForRock: [
	'A',
	'A J MALFI (EDS) | THE MESOZOIC FLOOD VOLCANISM ON THE PARANA BASIN: PETROGENETIC AND GEOPHYSICAL ASPECTS | SAO PAULO',
	'A N ZAITSEV (EDS) | PHOSCORITES AND CARBONATITES FROM MANTLE TO MINE: THE KEY EXAMPLE OF THE KOLA ALKALINE PROVINCE | MINERALOGICAL SOCIETY IF GREAT BRITAIN AND IRELAND',
	'A.',
	'A. J. MALFI',
	'A. J. | BONINITES AND RELATED ROCKS | UNWIN HYMAN',
	'A. J. | THE MESOZOIC FLOOD VOLCANISM OF THE PARAN?BASIN | INSTITUTO ASTRONOMICO E GEOFISICO',
	'A. | OPHIOLITS',
	'A.; HART',
	'ACTA GEOL. HISPANICA',
	'ACTA PETROL MINERAL (YANSHIKUANGWUXUEZAZHI)',
	'ACTA PETROL SINICA (YANSHIXUEBAO)',
	'ACTA PETROL. MINERAL.',
	'ACTA VULCANOL',
	'AM MINERAL',
	'AM. J. SCI.',
	'AMSTERDAM',
	'AND ATOLLS | AGU',
	'AND RELATED ROCKS | ELSEVIER',
	'ANN REP',
	'ANN. SER. TH SCI. GEOL.',
	'ANTARCTIC RES SER',
	'ANTARCTIC SCI',
	'ARNDT',
	'AUSTR. J. EARTH SCI.',
	'B H',
	'B. H.',
	'BARKER',
	'BASU',
	'BATIZA',
	'BLAISDELL',
	'BOGATIKOV',
	'BOL. GEOL. MINERO',
	'BULL GEOL SOC AM',
	'BULL GEOL SURV FINLAND',
	'BULL MINERAL',
	'BULL SERV GEOL ALGERIE',
	'BULL SOC GEOL FRANCE',
	'BULL VOLCANOL',
	'BULL VOLCANOL SOC JAPAN',
	'BULL. EARTHQUAKE RES. INST.',
	'BULL. GEOL. GREENLAND SURV.',
	'BULL. GEOL. SOC. GREENLAND',
	'BYULL MOSKOV OBSHCH ISPYT PRODIDY OTDEL GEOL',
	'C J HAWKESWORTH (EDS) | MANTLE METASOMATISM | ACADEMIC PRESS',
	'C. G.',
	'C. J. HAWKESWORTH',
	'C.-H. LO',
	'CAH INDOPACIFIQUE',
	'CAN J EARTH SCI',
	'CAN. MINERAL.',
	'CENT. EUR. GEOL.',
	'CH LO',
	'CHEM GEOL',
	'CHICHESTER',
	'CHIN J GEOCHEM',
	'CLERMONTFERRAND',
	'COLEMAN',
	'COMPT REND ACAD SCI PARIS SER A',
	'CONTRIB MINERAL PETROL',
	'CORPUS GEOL GALLAECIAE ND SER',
	'CRAWFORD',
	'D E | THE TECTONIC AND GEOLOGIC EVOLUTION OF SOUTHEAST ASIAN SEAS AND ISLANDS PART  | AGU',
	'D. W.',
	'DACITES',
	'DOKL ACAD SCI USSR',
	'DOKL EARTH SCI',
	'DORDRECHT',
	'E M PICCIRILLO',
	'E. G. NISBET',
	'E. G. | KOMATIITES | ALLEN',
	'E. M.',
	'E.E. RT AL.',
	'EARTH PLANET SCI LETT',
	'EARTH SCI',
	'EARTH SCI SECT',
	'ECON ENVIRON GEOL',
	'EE RT AL (EDS) | ULTRABASIC ROCKS | AKAD NAUK SSSR',
	'ELLIOT',
	'ESTUDIOS GEOL (MADRID)',
	'ESTUDIOS GEOL.',
	'ETHIOPIAN J. SCI.',
	'EUR J MINERAL',
	'F R BOYD',
	'F WALL',
	'F. | TRONDHJEMITES',
	'FRYER',
	'FDTANI KLY',
	'G W | SEAMOUNTS',
	'GEOACTA',
	'GEOCHEM INT',
	'GEOCHEM. J.',
	'GEOCHEMISTRY GEOPHYSICS GEOSYSTEMS',
	'GEOCHIM COSMOCHIM ACTA',
	'GEOCHIMICA',
	'GEOCHIMICA (DIQIUHUAXUE)',
	'GEODINAMICA ACTA',
	'GEOL CARPATHICA',
	'GEOL GEOFIZ',
	'GEOL MAG',
	'GEOL MINERAL',
	'GEOL MINERAL GEOGR GEOPHYS',
	'GEOL.',
	'GEOL. FOREN. STOCKHOLM FORH.',
	'GEOL. REV.',
	'GEOL. SURV. DEPT. MIN. ENERGY AFFAIRS REP. S. AFRICA BULL.',
	'GEOL. SURV. WEST. AUS.',
	'GEOLOGICAL CORRELATION | NAUKA',
	'GEOLOGY',
	'GEOPHYS RES LETT',
	'GEOSCIENCE FRONTIERS',
	'GEOSCIENCE JOURNAL',
	'GEOSCIENCE REPTS SHIZUOKA UNIV',
	'GEOSPHERE',
	'GONDWANA RES',
	'GRONLANDS GEOL. UNDERS. BULL.',
	'H O A MEYER (EDS) | THE MANTLE SAMPLE: INCLUSIONS IN KIMBERLITES AND OTHER VOLCANICS | AGU WASHINGTON',
	'H. O. A. MEYER',
	'HAYES',
	'HOKKAIDO UNIV',
	'HOUSTON',
	'INIT. REP. DEEP SEA DRILL. PROJ.',
	'INST GEOSCI',
	'INST. GEOL. GEOFIZ.',
	'INSTITUTO ASTRONOMICO E GEOFISICO',
	'INT GEOL REV',
	'INT J EARTH SCI (GEOL RUNDSCHAU)',
	'INT J GEOSCIENCES',
	'INT. OPHIOLITE SYMP. | NICOSIA',
	'ISLANDS',
	'J AFR EARTH SCI',
	'J EARTH SYST SCI',
	'J F | LE VOLCANISME DE LA REUNION | CENT RECH VOLCANOL',
	'J FAC SCI',
	'J GEODYNAMICS',
	'J GEOL',
	'J GEOL SOC AUSTRALIA',
	'J GEOL SOC JAPAN',
	'J GEOL SOC LONDON',
	'J GEOPHYS RES B',
	'J JILIN UNIV EARTH SCI ED (JILINDAXUEXUEBAO/GONGXUEBAN)',
	'J JPN ASSOC MINERAL PETROL ECON GEOL (GANSEKI KOBUTSU KOSHO GAKKAISHI)',
	'J KOREAN EARTH SCI SOC',
	'J MINER SOC KOREA',
	'J MINERAL PETROL (KUANGWUYANSHI)',
	'J MINERAL PETROL SCI',
	'J PETROL',
	'J SOUTHEAST ASIAN EARTH SCIENCES',
	'J VOLCANOL GEOTHERM RES',
	'J. ASIAN EARTH SCI.',
	'J. GEOGRAPHY',
	'J. JILIN UNIV. EARTH SCI. ED.',
	'J. JPN. ASSOC. MINERAL. PETROL. ECON. GEOL.',
	'J. M.; LOCKWOOD',
	'J. METAMORPHIC. GEOL.',
	'J. P. | MAUNA LOA REVEALED | AGU',
	'J. PETROL. SOC. KOREA',
	'J. S. AMER. EARTH SCI.',
	'J. SCI. HIROSHIMA UNIV.',
	'JAP MAGAZINE MIN PETROL SCI',
	'KEATING',
	'KUMAMOTO J. SCI.',
	'KYUSHU UNIV',
	'L. L.',
	'L. | THE AEOLIAN ISLANDS | ISTITUTO INTERNAZIONALE DI VULCANOLOGIA',
	'LAZKO',
	'LENAT',
	'LITHOS',
	'LONDON',
	'M F J FLOWER',
	'M MENZIES',
	'MAR. GEOL.',
	'MELFI',
	'MEM GEOL SOC AM',
	'MEM SOC GEOL IT',
	'MEM. FAC. EDUC. KUMAMOTO UNIV.',
	'MEM. FAC. SCI.',
	'MEM. GEOL. SOC. INDIA',
	'MINERAL MAG',
	'MINERAL PETROGR ACTA',
	'MINERAL PETROL  (SUPPL )',
	'MINERAL POLONICA',
	'MINERAL. PETROL.',
	'MOSCOW',
	'MUS. R. AFR. CENTR.-TERVUREN BELG.',
	'N. T.',
	'NATURE',
	'NEUES JAHRB MINERAL ABH',
	'NEW YORK',
	'NEW ZEALAND GEOL. SURVEY BULL.',
	'NEW ZEALAND J GEOL GEOPHYS',
	'NEWHALL',
	'NICOLAS',
	'NIXON',
	'O. A. | OCEANIC MAGMATISM - EVOLUTION',
	'OFIOLITI',
	'OPEN GEOSCIENCE',
	'ORE GEOL REV',
	'P',
	'P H NIXON (ED) | MANTLE XENOLITHS | WILEY',
	'P.',
	'P. H. NIXON',
	'PANAYIOTOU',
	'PER. MINERAL.',
	'PETERS',
	'PETROLOGY',
	'PHIL. TRANS. ROY. SOC. LONDON A',
	'PHILIPPINES | UNIV. WASHINGTON PRESS',
	'PHYS CHEM EARTH',
	'PHYS EARTH PLANET INTERIORS',
	'PREC RESEARCH',
	'PROC. OCEAN DRILL. PROGRAM',
	'PUNONGBAYAN',
	'R BOEHLERT',
	'R G | OPHIOLITE GENESIS AND EVOLUTION OF THE OCEANIC LITHOSPHERE | KLUWER',
	'R. S. | FIRE AND MUD. ERUPTIONS AND LAHARS OF MOUNT PINATUBO',
	'READING THE ISOTOPIC CODE | AGU',
	'REND SOC ITAL MINERAL PETROL',
	'REPT. CENTER INSTRUMENT. ANAL.',
	'REPT. FAC. SCI. SHIZUOKA UNIV.',
	'REPT. RES. INST. INDUST. SCI.',
	'RESOURCE GEOL.',
	'REV ASOC GEOL ARGENTINA',
	'REV. MEX. CIENC. GEOL.',
	'RHODES',
	'RUSS GEOL GEOPHYS',
	'RUSS. J. PACIFIC GEOL.',
	'S AFR J GEOL',
	'S. R. | EARTH PROCESSES',
	'S.-L. CHUNG',
	'SCHOLL',
	'SCI CHINA EARTH SCI',
	'SCI CHINA SER D EARTH SCI  (SUPPL)',
	'SCI REPT INST GEOSCI',
	'SCI REPT KANAZAWA UNIV',
	'SCI REPT OF NIIGATA UNIV',
	'SCI REPT TOHOKU UNIV',
	'SCI. REP. NAT. TAIWAN UNIV.',
	'SCI. REPT. SAITAMA UNIV./B',
	'SCIENT. RESULTS',
	'SEATTLE AND LONDON',
	'SEC.',
	'SECT',
	'SEPC PUBL GEOL SOC LONDON',
	'SER',
	'SER D GEOLOGY',
	'SER. B',
	'SERIES E: GEOL AND MIN',
	'SIBIRSKOE OTDEL',
	'SOV. GEOL. GEOPHYS.',
	'SPEC PAP GEOL SOC AM',
	'SPEC PUBL GEOL SOC S AFR',
	'T. L. | GEOLOGY AND OFFSHORE RESOURCES OF PACIFIC ISLAND ARCS - TONGA REGION | CIRCUM-PACIFIC COUNCIL FOR ENERGY AND MINERAL RESOURCES',
	'T.-Y. LEE',
	'T.J.',
	'TECTONOPHYSICS',
	'TEXAS',
	'THE ISLAND ARC',
	'TJ',
	'TR. AKAD. NAUK SSSR',
	'TRANS ACAD SCI USSR GEOL SER',
	'TRANS GEOL SOC SOUTH AFRICA',
	'TSCHERMAKS MINERAL PETROGR MITT',
	'TURKISH J. OF EARTH SCIENCES',
	'TY LEE (EDS) | MANTLE DYNAMICS AND PLATE INTERACTIONS IN EAST ASIA | AGU',
	'U S GEOL SURV BULL',
	'U S GEOL SURV OPEN FILE REPT',
	'U. S. GEOL. SURV. PROF. PAP.',
	'UK',
	'UNIV TOKYO',
	'UNIV TSUKUBA',
	'UNIVERSIDADE DE SAO PAULO',
	'VALLIER',
	'VILLARI',
	'VISINDAFELAG ISLENDINGA',
	'VOLC. SEIS.',
	'VOLCANOL. SEISMOL.',
	'WASHINGTON DC',
	'YAMAGUCHI UNIVERSITY',
	'YEAR BOOK CARNEGIE INST. WASHINGTON',
	],

	journalForMineral: [
		'A',
		'A J MALFI (EDS) | THE MESOZOIC FLOOD VOLCANISM ON THE PARANA BASIN: PETROGENETIC AND GEOPHYSICAL ASPECTS | SAO PAULO',
		'A N ZAITSEV (EDS) | PHOSCORITES AND CARBONATITES FROM MANTLE TO MINE: THE KEY EXAMPLE OF THE KOLA ALKALINE PROVINCE | MINERALOGICAL SOCIETY IF GREAT BRITAIN AND IRELAND',
		'A.',
		'A. B. KAMPUNZU',
		'A. J. MALFI',
		'A. J. | BONINITES AND RELATED ROCKS | UNWIN HYMAN',
		'A. J. | THE MESOZOIC FLOOD VOLCANISM OF THE PARAN?BASIN | INSTITUTO ASTRONOMICO E GEOFISICO',
		'A. M. BEN ASHOUR',
		'A. N. ZAITSEV',
		'A. | OPHIOLITS',
		'A.; HART',
		'ACTA GEOL. HISPANICA',
		'ACTA PETROL MINERAL (YANSHIKUANGWUXUEZAZHI)',
		'ACTA PETROL SINICA (YANSHIXUEBAO)',
		'ACTA PETROL. MINERAL.',
		'ACTA UNIV. CAROLINAE GEOL.',
		'ACTA VULCANOL',
		'AEGEAN EARTH SCI.',
		'AFR. GEOSCIENCE REV.',
		'AFR. STUDIES MONOGR.',
		'AM MINERAL',
		'AM. J. SCI.',
		'AMSTERDAM',
		'AN. ACAD. BRASIL. CIENC.',
		'AN. SOC. GEOL. BELGIQUES',
		'AND ATOLLS | AGU',
		'AND RELATED ROCKS | ELSEVIER',
		'AND. GEOL.',
		'ANN REP',
		'ANN. MUS. ROYAL AFR',
		'ANN. SER. TH SCI. GEOL.',
		'ANTARCTIC RES SER',
		'ANTARCTIC SCI',
		'AOKI',
		'ARCH. MINERAL.',
		'ARMENTA',
		'ARNDT',
		'ATTI CONVEGNI LINCEI ACCAD. NAZ. LINCEI',
		'AUSTR. J. EARTH SCI.',
		'B H',
		'B.',
		'B. H.',
		'BARKER',
		'BASU',
		'BATIZA',
		'BER. KGL. PREUSS. AKAD. WISS.',
		'BERLINER GEOWISS. ABH. A',
		'BLAISDELL',
		'BOCHUMER GEOL. GEOTECHN. ARBEITEN',
		'BOEHLERT',
		'BOGATIKOV',
		'BOL. GEOL. MINERO',
		'BRITISH ANTARCTIC SURV. SCIENT. REP.',
		'BROCHER',
		'BULL GEOL SOC AM',
		'BULL GEOL SURV FINLAND',
		'BULL MINERAL',
		'BULL SERV GEOL ALGERIE',
		'BULL SOC GEOL FRANCE',
		'BULL VOLCANOL',
		'BULL VOLCANOL SOC JAPAN',
		'BULL. COLL. SCI.',
		'BULL. EARTHQUAKE RES. INST.',
		'BULL. GEOL. GREENLAND SURV.',
		'BULL. GEOL. SOC. AM. PART II',
		'BULL. GEOL. SOC. DENMARK',
		'BULL. GEOL. SURV. JAPAN',
		'BULL. PIRPSEV',
		'BULL. SOC. FR. MINERAL.',
		'BULL. SOC. FR. MINERAL. CRISTALLOGR.',
		'BYULL MOSKOV OBSHCH ISPYT PRODIDY OTDEL GEOL',
		'C J HAWKESWORTH (EDS) | MANTLE METASOMATISM | ACADEMIC PRESS',
		'C. G.',
		'C. J. HAWKESWORTH',
		'C.-H. LO',
		'CAH INDOPACIFIQUE',
		'CAN J EARTH SCI',
		'CENT. EUR. GEOL.',
		'CENTRALE',
		'CH LO',
		'CHEM GEOL',
		'CHICHESTER',
		'CHIN J GEOCHEM',
		'CLERMONT-FERRAND',
		'COLEMAN',
		'COMPT REND ACAD SCI PARIS SER A',
		'COMPT. REND. GEOSCIENCE',
		'CONTRIB MINERAL PETROL',
		'CORPUS GEOL GALLAECIAE ND SER',
		'CRAWFORD',
		'D E | THE TECTONIC AND GEOLOGIC EVOLUTION OF SOUTHEAST ASIAN SEAS AND ISLANDS PART  | AGU',
		'D. W.',
		'DACITES',
		'DOKL ACAD SCI USSR',
		'DOKL EARTH SCI',
		'DORDRECHT',
		'E M PICCIRILLO',
		'E. G. NISBET',
		'E. G. | KOMATIITES | ALLEN',
		'E. M.',
		'E.E. RT AL.',
		'EARTH PLANET SCI LETT',
		'EARTH SCI',
		'EARTH SCI SECT',
		'ECON ENVIRON GEOL',
		'EE RT AL (EDS) | ULTRABASIC ROCKS | AKAD NAUK SSSR',
		'ELLIOT',
		'ESTUDIOS GEOL (MADRID)',
		'ESTUDIOS GEOL.',
		'ETHIOPIAN J. SCI.',
		'EUR J MINERAL',
		'EUR. J. MINERAL. BH.',
		'F R BOYD',
		'F WALL',
		'F. | TRONDHJEMITES',
		'FDTANI KLY',
		'FRYER',
		'G W | SEAMOUNTS',
		'GARCIA DE ORTA',
		'GEOACTA',
		'GEOCHEM INT',
		'GEOCHEM. J.',
		'GEOCHEMISTRY GEOPHYSICS GEOSYSTEMS',
		'GEOCHIM COSMOCHIM ACTA',
		'GEOCHIMICA',
		'GEOCHIMICA (DIQIUHUAXUE)',
		'GEODINAMICA ACTA',
		'GEOFIS. INT.',
		'GEOL CARPATHICA',
		'GEOL GEOFIZ',
		'GEOL MAG',
		'GEOL MINERAL',
		'GEOL MINERAL GEOGR GEOPHYS',
		'GEOL.',
		'GEOL. FOREN. STOCKHOLM FORH.',
		'GEOL. JB. B',
		'GEOL. REV.',
		'GEOL. ROMANA',
		'GEOL. SURV. CAN. MEM.',
		'GEOL. SURV. DEPT. MIN. ENERGY AFFAIRS REP. S. AFRICA BULL.',
		'GEOL. SURV. WEST. AUS.',
		'GEOLOGIA SUDETICA',
		'GEOLOGICAL CORRELATION | NAUKA',
		'GEOLOGY',
		'GEOPHYS RES LETT',
		'GEOSCIENCE FRONTIERS',
		'GEOSCIENCE JOURNAL',
		'GEOSCIENCE REPTS SHIZUOKA UNIV',
		'GEOSPHERE',
		'GEOTECTONICS',
		'GONDWANA RES',
		'GRONLANDS GEOL. UNDERS. BULL.',
		'H O A MEYER (EDS) | THE MANTLE SAMPLE: INCLUSIONS IN KIMBERLITES AND OTHER VOLCANICS | AGU WASHINGTON',
		'H. O. A. MEYER',
		'H.; IIZUKA',
		'HAYES',
		'HOKKAIDO UNIV',
		'HOUSTON',
		'INIT. REP. DEEP SEA DRILL. PROJ.',
		'INST GEOSCI',
		'INST. GEOL. GEOFIZ.',
		'INST. GEOL. SCI. NAT. ENVIRON. RES. COUNCIL REPT. /',
		'INSTITUTO ASTRONOMICO E GEOFISICO',
		'INT GEOL REV',
		'INT J EARTH SCI (GEOL RUNDSCHAU)',
		'INT J GEOSCIENCES',
		'INT. OPHIOLITE SYMP. | NICOSIA',
		'ISLANDS',
		'J AFR EARTH SCI',
		'J EARTH SYST SCI',
		'J F | LE VOLCANISME DE LA REUNION | CENT RECH VOLCANOL',
		'J FAC SCI',
		'J GEODYNAMICS',
		'J GEOL',
		'J GEOL SOC AUSTRALIA',
		'J GEOL SOC JAPAN',
		'J GEOL SOC LONDON',
		'J GEOPHYS RES B',
		'J JILIN UNIV EARTH SCI ED (JILINDAXUEXUEBAO/GONGXUEBAN)',
		'J JPN ASSOC MINERAL PETROL ECON GEOL (GANSEKI KOBUTSU KOSHO GAKKAISHI)',
		'J KOREAN EARTH SCI SOC',
		'J MINER SOC KOREA',
		'J MINERAL PETROL (KUANGWUYANSHI)',
		'J MINERAL PETROL SCI',
		'J PETROL',
		'J SOUTHEAST ASIAN EARTH SCIENCES',
		'J VOLCANOL GEOTHERM RES',
		'J. ASIAN EARTH SCI.',
		'J. C.',
		'J. CHINA UNIV. GEOSCIENCES - EARTH SCI.',
		'J. CZECH GEOL. SOC.',
		'J. EARTH SCI. NAGOYA UNIVERSITY',
		'J. ET AL. | KIMBERLITES AND RELATED ROCKS | GEOL. SOC. AUSTRALIA',
		'J. GEOCHEM. EXPLORATION',
		'J. GEOGRAPHY',
		'J. GEOL. SOC. CHINA',
		'J. GEOL. SOC. KOREA',
		'J. JILIN UNIV. EARTH SCI. ED.',
		'J. JPN. ASSOC. MINERAL. PETROL. ECON. GEOL.',
		'J. KORNPROBST',
		'J. M.; LOCKWOOD',
		'J. METAMORPHIC. GEOL.',
		'J. P. | MAUNA LOA REVEALED | AGU',
		'J. ROYAL SOC. NEW ZEALAND',
		'J. S. AMER. EARTH SCI.',
		'J. SCI. HIROSHIMA UNIV.',
		'J. VOLCANOL. SEISMOL.',
		'JAP MAGAZINE MIN PETROL SCI',
		'KEATING',
		'KUMAMOTO J. SCI.',
		'KYUSHU UNIV',
		'L. L.',
		'L. | THE AEOLIAN ISLANDS | ISTITUTO INTERNAZIONALE DI VULCANOLOGIA',
		'LAZKO',
		'LENAT',
		'LIHTOS -',
		'LITHOL. MINERAL RESOURCES',
		'LITHOS',
		'LONDON',
		'M F J FLOWER',
		'M MENZIES',
		'M. J. SALEM',
		'M. T. BUSREWIL',
		'MAR. GEOPHYS. RES.',
		'MAR. MINING',
		'MEDDR. GROENLAND',
		'MELFI',
		'MEM GEOL SOC AM',
		'MEM SOC GEOL IT',
		'MEM. DOC. CENTRE ARM. ET. STRUCT. SOCLES RENNES',
		'MEM. FAC. EDUC. KUMAMOTO UNIV.',
		'MEM. FAC. SCI.',
		'MINERAL MAG',
		'MINERAL PETROGR ACTA',
		'MINERAL PETROL  (SUPPL )',
		'MINERAL POLONICA',
		'MINERAL. PETROL.',
		'MOSCOW',
		'MUS. R. AFR. CENTR.-TERVUREN BELG.',
		'N. T.',
		'NATURE',
		'NEUES JAHRB MINERAL ABH',
		'NEW YORK',
		'NEW ZEALAND GEOL. SURVEY BULL.',
		'NEW ZEALAND J GEOL GEOPHYS',
		'NEWHALL',
		'NICOLAS',
		'NIXON',
		'NORDIC VOLCANOL. INST. REPORT -',
		'NORSK GEOL. TIDSSKRIFT',
		'O. A. | OCEANIC MAGMATISM - EVOLUTION',
		'OFIOLITI',
		'OPEN FILE M./',
		'OPEN GEOSCIENCE',
		'ORE GEOL REV',
		'P',
		'P H NIXON (ED) | MANTLE XENOLITHS | WILEY',
		'P.',
		'P. H. NIXON',
		'PACIFIC SCI.',
		'PANAYIOTOU',
		'PERTH',
		'PETERS',
		'PETROLOGIYA',
		'PHIL. TRANS. ROY. SOC. LONDON A',
		'PHILIPPINES | UNIV. WASHINGTON PRESS',
		'PHYS CHEM EARTH',
		'PHYS EARTH PLANET INTERIORS',
		'POLAR RES.',
		'PREC RESEARCH',
		'PROC. OCEAN DRILL. PROGRAM',
		'PROC. TH INTERN. KIMBERLITE CONF. VOL.',
		'PUNONGBAYAN',
		'QUATERNARY GEOCHRON.',
		'R G | OPHIOLITE GENESIS AND EVOLUTION OF THE OCEANIC LITHOSPHERE | KLUWER',
		'R.',
		'R. S. | FIRE AND MUD. ERUPTIONS AND LAHARS OF MOUNT PINATUBO',
		'R. T. LUBALA',
		'READING THE ISOTOPIC CODE | AGU',
		'REND SOC ITAL MINERAL PETROL',
		'REPT. CENTER INSTRUMENT. ANAL.',
		'REPT. FAC. SCI. SHIZUOKA UNIV.',
		'REPT. RES. INST. INDUST. SCI.',
		'RESOURCE GEOL.',
		'REV ASOC GEOL ARGENTINA',
		'REV. BRAS. GEOCIENC.',
		'REV. MEX. CIENC. GEOL.',
		'REV. SOC. GEOL. ESPANA',
		'RHODES',
		'ROSS',
		'RUSS GEOL GEOPHYS',
		'RUSS. J. PACIFIC GEOL.',
		'S AFR J GEOL',
		'S. R. | EARTH PROCESSES',
		'S. | VOLCANOES AND TECTONOSPHERE | TOKAI UNIV. PRESS',
		'S.-L. CHUNG',
		'SAAVEDRA',
		'SANTACROCE',
		'SCHOLL',
		'SCI CHINA EARTH SCI',
		'SCI CHINA SER D EARTH SCI  (SUPPL)',
		'SCI REPT INST GEOSCI',
		'SCI REPT KANAZAWA UNIV',
		'SCI REPT OF NIIGATA UNIV',
		'SCI REPT TOHOKU UNIV',
		'SCI. REP. NAT. TAIWAN UNIV.',
		'SCI. REPT. SAITAMA UNIV./B',
		'SCIENCE',
		'SCIENT. RESULTS',
		'SEATTLE AND LONDON',
		'SEC.',
		'SECT',
		'SEISMOL. GEOL.',
		'SEPC PUBL GEOL SOC LONDON',
		'SER',
		'SER D GEOLOGY',
		'SER. B',
		'SERIES E: GEOL AND MIN',
		'SIBIRSKOE OTDEL',
		'SOV. GEOL. GEOPHYS.',
		'SPEC PAP GEOL SOC AM',
		'SPEC PUBL GEOL SOC S AFR',
		'SUPPL. ISSUE',
		'SYDNEY',
		'T. L. | GEOLOGY AND OFFSHORE RESOURCES OF PACIFIC ISLAND ARCS - TONGA REGION | CIRCUM-PACIFIC COUNCIL FOR ENERGY AND MINERAL RESOURCES',
		'T. M. | INVESTIGATIONS OF THE NORTHERN MELANESIAN BORDERLAND | CIRCUM-PACIFIC COUNCIL FOR ENERGY AND MINERAL RESOURCES',
		'T.-Y. LEE',
		'T.J.',
		'TECTONOPHYSICS',
		'TERRA COGNITA',
		'TEXAS',
		'THE ISLAND ARC',
		'TJ',
		'TOKYO',
		'TR. AKAD. NAUK SSSR',
		'TRANS ACAD SCI USSR GEOL SER',
		'TRANS GEOL SOC SOUTH AFRICA',
		'TRANS. NAT. INST. SCI. INDIA',
		'TSCHERMAKS MINERAL PETROGR MITT',
		'TURKISH J. OF EARTH SCIENCES',
		'TY LEE (EDS) | MANTLE DYNAMICS AND PLATE INTERACTIONS IN EAST ASIA | AGU',
		'U S GEOL SURV BULL',
		'U S GEOL SURV OPEN FILE REPT',
		'U. S. GEOL. SURV. PROF. PAP.',
		'UK',
		'UNIV TOKYO',
		'UNIV TSUKUBA',
		'UNIV. RYUKYUS',
		'UNIVERSIDADE DE SAO PAULO',
		'V. A.',
		'VALLIER',
		'VILLARI',
		'VISINDAFELAG ISLENDINGA',
		'VOLC. SEIS.',
		'WASHINGTON DC',
		'YAMAGUCHI UNIVERSITY',
		'YEAR BOOK CARNEGIE INST. WASHINGTON',
		'Z. GEOL. WISS.',
		'Z. VULKANOL.',
	],

	journalForExperiment: [
		"American Mineralogist",
		"Chemical Geology",
		"Earth and Planetary Science Letters",
		"Geochimica Et Cosmochimica Acta",
		"Geochimica et Cosmochimica Acta",
		"Journal of Geophysical Research: Planets",
		"Journal of Petrology",
		"Nature",
		"Nature Geoscience"
	],
}
